include(ExternalProject)

set(BREAKPAD_SOURCE_DIR ${CMAKE_SOURCE_DIR}/../third_party/breakpad)
set(BREAKPAD_BUILD_DIR ${CMAKE_CURRENT_BINARY_DIR}/breakpad_build})
set(BREAKPAD_CLIENT_LIB ${BREAKPAD_BUILD_DIR}/libbreakpad.a)
set(BREAKPAD_COMMON_LIB ${BREAKPAD_BUILD_DIR}/libbreakpad_common.a)
set(BREAKPAD_OUTPUTS ${BREAKPAD_CLIENT_LIB} ${BREAKPAD_COMMON_LIB})
set(BREAKPAD_TOPLEVEL_INCLUDE_DIR ${BREAKPAD_SOURCE_DIR}/src)

if (WIN32)
  set(BREAKPAD_CLIENT_INCLUDE_DIR ${BREAKPAD_SOURCE_DIR}/src/client/windows)
elseif (APPLE)
  set(BREAKPAD_CLIENT_INCLUDE_DIR ${BREAKPAD_SOURCE_DIR}/src/client/mac)
else()
  set(BREAKPAD_CLIENT_INCLUDE_DIR ${BREAKPAD_SOURCE_DIR}/src/client/linux)
endif()

ExternalProject_Add(breakpad_proj
  SOURCE_DIR ${BREAKPAD_SOURCE_DIR}
  BINARY_DIR ${BREAKPAD_BUILD_DIR}
  BUILD_BYPRODUCTS ${BREAKPAD_OUTPUTS}
)
