name: prepare_build_ubuntu_latest
description: Prepare ubuntu-latest for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - name: Install dependencies
    if: always()
    shell: bash
    env:
       PIP_BREAK_SYSTEM_PACKAGES: 1
       DEBIAN_FRONTEND: noninteractive
    run: |
       sudo apt-get update
       sudo apt-get -y install $(distribution/dependencies/get_dependencies.sh build_base_ubuntu_latest)
       sudo $PIP install --upgrade pip build auditwheel patchelf toml jinja2