name: prepare_build_ubuntu_latest
description: Prepare ubuntu-latest for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - name: Install dependencies
    shell: bash
    run: sudo DEBIAN_FRONTEND=noninteractive apt-get -y install $(distribution/dependencies/get_dependencies.sh build_base_debian)