name: prepare_build_ubuntu_latest
description: Prepare ubuntu-latest for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - name: Install dependencies
    shell: bash
    run: |
       sudo DEBIAN_FRONTEND=noninteractive apt-get update
       sudo DEBIAN_FRONTEND=noninteractive apt-get -y install $(distribution/dependencies/get_dependencies.sh build_base_ubuntu_latest)
       PIP_BREAK_SYSTEM_PACKAGES=1 sudo python3 -m pip install --upgrade pip build auditwheel patchelf
  - name: TMate failure session
    uses: SanderVocke/action-tmate@master