name: Checkpoint setup
description: Checkpoint in the workflow.

inputs:
  shell:
    description: "Shell to use for wrapping"
    required: true

runs:
  using: "composite"
  steps:
  - name: Setup Shell Wrapper
    uses: sandervocke/setup-shell-wrapper@v1
  - name: Setup shells
    shell: bash
    run: |
      echo "BASE_WRAP_SHELL=${{ inputs.shell }}" >> $GITHUB_ENV
      echo "WRAP_SHELL=bash scripts/gha_bash_with_custom_fail.sh" >> $GITHUB_ENV
      echo "failure_status=" >> $GITHUB_ENV
  - name: Background tmate
    if: always() && env.failure_status == 'unhandled' && env.checkpoints_enabled == 'true'
    uses: SanderVocke/action-tmate@master
    with:
       detached: true
