[package]
name = "packaging"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "package"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
backend = { path = "../backend" }

walkdir = { workspace = true }
glob = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true }
copy_dir = { workspace = true }
tempfile = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
ctor = { workspace = true }
clap = { workspace = true, features = ["derive"] }

[features]
# Dummy build to build dependencies only
prebuild = ["common/prebuild", "backend/prebuild"]