[package]
name = "packaging"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "package"
path = "src/main.rs"

[dependencies]
walkdir = "2"
glob = "0.3"
anyhow = "1.0"
regex = "1.10"
copy_dir = "0.1"
tempfile = "3.12"
indexmap = "2.5"
log = "0.4"
ctor = "0.2"
clap = { version = "4.5", features = ["derive"] }
common = { path = "../common" }

[features]
# Dummy build to build dependencies only
prebuild = ["common/prebuild"]