# Top-level build script.

inputs:
  name:
    description: "Name for the build"
  release_build:
    description: "if true, does a release build. Otherwise, a debug build."
    default: 'false'
  cmake_opts:
    description: "CMake options"
  prepare_kind:
    description: "Which prepare function to call (see prepare action)"
  python:
    description: "Python command to use"
  platform:
    description: "platform descriptor"
  package_kind:
    description: "Kind of package to build"
  second_package_kind:
    description: "Kind of package to build (additional)"
    default: null
  third_package_kind:
    description: "Kind of package to build (additional)"
    default: null
  coverage:
    description: "Whether to run coverage"
  upload_artifacts:
    description: "Whether to upload artifacts"
    default: 'true'
  upload_release_assets:
    default: 'false'
    description: "Whether to attempt uploading assets to a tag release."
  GITHUB_TOKEN:
    required: true
    description: "GitHub token"
  macos_target_version:
    required: false
    description: "macOS target version"
  vcpkg_rebuild:
    description: "whether to rebuild vcpkg packages"
  sentry_auth_token:
    type: string

runs:
  using: "composite"
  steps:
  - name: Store cwd
    if: always()
    shell: wrap-shell {0}
    id: cwd
    run: |
        echo "cwd=$(pwd)" | tee -a $GITHUB_OUTPUT
  - shell: wrap-shell {0}
    if: always()
    run: |
      printf "\n\n\n\n\n\n"
      echo "=========================================="
      echo "Preparing environment"
      echo "=========================================="
      printf "\n\n\n\n\n\n"
  - name: Download upload URL for release assets
    if: always() && inputs.upload_release_assets == 'true'
    uses: actions/download-artifact@v4
    with:
      name: release_upload_assets_url
      path: release_upload_assets_url
  - name: Set upload URL for release assets
    if: always() && inputs.upload_release_assets == 'true'
    shell: bash
    run: echo "release_upload_assets_url=$(cat release_upload_assets_url/release_upload_assets_url.txt)" | tee -a $GITHUB_ENV
  - name: set Cargo build flags (release)
    if: always() && inputs.release_build == 'true'
    shell: wrap-shell {0}
    run: |
      echo "ARTIFACT_VARIANT=release-${{ inputs.platform }}" | tee -a $GITHUB_ENV
      echo "CARGO_ARTIFACTS_DIR=$(${{ env.CONVERT_PATH_FN }} $(pwd)/target/release-with-debug)" | tee -a $GITHUB_ENV
  - name: set Cargo build flags (debug)
    if: always() && inputs.release_build != 'true'
    shell: wrap-shell {0}
    run: |
      echo "ARTIFACT_VARIANT=debug-${{ inputs.platform }}" | tee -a $GITHUB_ENV
      echo "CARGO_ARTIFACTS_DIR=$(${{ env.CONVERT_PATH_FN }} $(pwd)/target/debug)" | tee -a $GITHUB_ENV
  - name: More env settings
    shell: wrap-shell {0}
    if: always()
    run: |
      echo "PYTHON=${{ inputs.python }}" | tee -a $GITHUB_ENV
      echo "PIP=${{ inputs.python }} -m pip" | tee -a $GITHUB_ENV
      echo "PYTEST=${{ inputs.python }} -m pytest" | tee -a $GITHUB_ENV
      echo "PLATFORM=${{ inputs.platform }}" | tee -a $GITHUB_ENV
  - uses: ./.github/actions/checkpoint
    if: always()
  - name: Install Qoverage
    if: always() && inputs.coverage
    uses: ./.github/actions/install_qoverage
  - name: Prepare
    if: always()
    id: prepare
    uses: ./.github/actions/prepare_build
    with:
      variant: ${{ inputs.prepare_kind }}
      GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      macos_target_version: ${{ inputs.macos_target_version }}
      vcpkg_rebuild: ${{ inputs.vcpkg_rebuild }}
      pip: ${{ inputs.python }} -m pip

  - uses: ./.github/actions/checkpoint
    if: always()
  - uses: ./.github/actions/checkpoint
    if: always()
  - shell: wrap-shell {0}
    if: always()
    run: |
      printf "\n\n\n\n\n\n"
      echo "=========================================="
      echo "Building"
      echo "=========================================="
      printf "\n\n\n\n\n\n"
  - name: Build
    if: always()
    id: build_base
    uses: ./.github/actions/build_base
    with:
        release_build: ${{ inputs.release_build }}
  - name: Qoverage - Instrument QML files
    if: always() && inputs.coverage
    uses: ./.github/actions/qoverage_instrument
    with:
      package_path: .
  - uses: ./.github/actions/checkpoint
    if: always()
  - shell: wrap-shell {0}
    if: always() && inputs.package_kind
    run: |
      printf "\n\n\n\n\n\n"
      echo "=========================================="
      echo "Build package: ${{ inputs.package_kind }}"
      echo "=========================================="
      printf "\n\n\n\n\n\n"
  - name: Build package
    id: package
    if: always() && inputs.package_kind
    uses: ./.github/actions/build_package
    with:
      package_kind: ${{ inputs.package_kind }}
      upload_release_assets: ${{ inputs.upload_release_assets }}
      release_upload_assets_url: ${{ env.release_upload_assets_url }}
      sentry_auth_token: ${{ inputs.sentry_auth_token }}
  - uses: ./.github/actions/checkpoint
    if: always()
  - shell: wrap-shell {0}
    if: always() && inputs.second_package_kind
    run: |
      printf "\n\n\n\n\n\n"
      echo "=========================================="
      echo "Build package: ${{ inputs.second_package_kind }}"
      echo "=========================================="
      printf "\n\n\n\n\n\n"
  - name: Build second package
    id: second_package
    if: always() && inputs.second_package_kind
    uses: ./.github/actions/build_package
    with:
      package_kind: ${{ inputs.second_package_kind }}
      upload_release_assets: ${{ inputs.upload_release_assets }}
      release_upload_assets_url: ${{ env.release_upload_assets_url }}
      sentry_auth_token: ${{ inputs.sentry_auth_token }}
  - uses: ./.github/actions/checkpoint
    if: always()
  - shell: wrap-shell {0}
    if: always() && inputs.third_package_kind
    run: |
      printf "\n\n\n\n\n\n"
      echo "=========================================="
      echo "Build package: ${{ inputs.third_package_kind }}"
      echo "=========================================="
      printf "\n\n\n\n\n\n"
  - name: Build third package
    id: third_package
    if: always() && inputs.third_package_kind
    uses: ./.github/actions/build_package
    with:
      package_kind: ${{ inputs.third_package_kind }}
      upload_release_assets: ${{ inputs.upload_release_assets }}
      release_upload_assets_url: ${{ env.release_upload_assets_url }}
      sentry_auth_token: ${{ inputs.sentry_auth_token }}
  - uses: ./.github/actions/checkpoint
    if: always()
  - shell: wrap-shell {0}
    if: always()
    run: |
      printf "\n\n\n\n\n\n"
      echo "=========================================="
      echo "Upload artifacts"
      echo "=========================================="
      printf "\n\n\n\n\n\n"
  - name: Upload vcpkg-generated dependency builds
    if: always() && inputs.upload_artifacts == 'true'
    uses: actions/upload-artifact@v4
    with:
      name: vcpkg_dependencies_installed_${{ inputs.name }}
      path: build/vcpkg_installed
  # - name: Upload debug info
  #   if: always() && inputs.upload_artifacts == 'true'
  #   uses: actions/upload-artifact@v4
  #   with:
  #     name: breakpad_debuginfo_${{ inputs.name }}
  #     path: debuginfo
  - name: Save build info for coverage analyis
    shell: wrap-shell {0}
    if: always() && inputs.coverage
    run: |
      echo "$(realpath build/cp*/)" | tee ori_build_dir.txt
  - name: Upload info context for coverage analysis
    if: always() && inputs.coverage && inputs.upload_artifacts == 'true'
    uses: actions/upload-artifact@v4
    with:
      name: coverage_context
      path: |
        ./**/*.gcno
        ori_build_dir.txt
  # - name: Upload .PDB files
  #   if: always() && inputs.prepare_kind == 'windows' && inputs.upload_artifacts == 'true'
  #   uses: actions/upload-artifact@v4
  #   with:
  #     name: pdb_${{ inputs.name }}
  #     path: |
  #       ./target/**/*.pdb
  #       ./target/**/*.PDB
  - uses: ./.github/actions/checkpoint
    if: always()
  - shell: wrap-shell {0}
    if: always()
    run: |
      printf "\n\n\n\n\n\n"
      echo "=========================================="
      echo "Upload release assets"
      echo "=========================================="
      printf "\n\n\n\n\n\n"
  - name: Compress debug info
    if: always() && env.release_upload_assets_url
    id: compress_debug_info
    shell: bash
    run: |
      tar -czf ${{ inputs.name }}_breakpad_debug_info.tar.gz debuginfo
      echo "path=${{ inputs.name }}_breakpad_debug_info.tar.gz" | tee -a $GITHUB_OUTPUT
  - name: Upload Breakpad debug info
    if: always() && env.release_upload_assets_url
    uses: shogo82148/actions-upload-release-asset@v1
    with:
      upload_url: ${{ env.release_upload_assets_url }}
      asset_path: ${{ steps.compress_debug_info.outputs.path }}
  - name: Compress PDB files
    if: always() && env.release_upload_assets_url && inputs.prepare_kind == 'windows'
    id: compress_pdb
    shell: bash
    run: |
      find target -name "*.pdb" -o -name "*.PDB" | tar -czf ${{ inputs.name }}_pdb_files.tar.gz -T -
      echo "path=${{ inputs.name }}_pdb_files.tar.gz" | tee -a $GITHUB_OUTPUT
  - name: Upload PDB files
    if: always() && env.release_upload_assets_url && inputs.prepare_kind == 'windows'
    uses: shogo82148/actions-upload-release-asset@v1
    with:
      upload_url: ${{ env.release_upload_assets_url }}
      asset_path: ${{ steps.compress_pdb.outputs.path }}