[package]
name = "shoop_py_utils"
edition = "2021"

[dependencies]
pyo3 = { version = "0.25", features = ["auto-initialize"] }
cxx-qt = "0.7"
cxx-qt-lib = { version = "0.7", features = ["full"] }

[build-dependencies]

[features]
# Dummy build to build dependencies only
prebuild = []