[package]
name = "shoopdaloop_egui"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
eframe = { workspace = true }
shoop_app = { path = "../shoop_app" }
shoop_backend = { path = "../shoop_backend" }
shoop_egui = { path = "../shoop_egui" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
log = { workspace = true }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-time = "1.1"
web-sys = { version = "0.3", features = [
    "Document",
    "Element",
    "HtmlCanvasElement",
    "Location",
    "Window",
] }

[lints]
workspace = true
