[package]
name = "shoopdaloop_egui"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
eframe = { workspace = true }
shoop_app = { path = "../shoop_app" }
shoop_backend = { path = "../shoop_backend" }
shoop_egui = { path = "../shoop_egui" }
shoop_scripting = { path = "../shoop_scripting" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
shoop_backend = { path = "../shoop_backend", features = ["native-drivers"] }
shoop_settings = { path = "../shoop_settings", features = ["native-store"] }
rfd = { workspace = true, default-features = false, features = ["xdg-portal", "async-std"] }
rodio = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
shoop_settings = { path = "../shoop_settings" }
rfd = { workspace = true, features = ["xdg-portal", "async-std"] }
js-sys = "0.3"
log = { workspace = true }
serde_json = { workspace = true }
shoop_audio_protocol = { path = "../shoop_audio_protocol" }
shoop_session = { path = "../shoop_session" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-time = "1.1"
web-sys = { version = "0.3", features = [
    "AudioContext",
    "AudioBuffer",
    "AudioBufferSourceNode",
    "AudioContextState",
    "AudioDestinationNode",
    "AudioNode",
    "AudioScheduledSourceNode",
    "AudioWorklet",
    "AudioWorkletNode",
    "AudioWorkletNodeOptions",
    "Document",
    "Element",
    "Event",
    "EventTarget",
    "HtmlButtonElement",
    "HtmlCanvasElement",
    "Location",
    "MediaDevices",
    "MediaStream",
    "MediaStreamAudioSourceNode",
    "MediaStreamConstraints",
    "MediaStreamTrack",
    "MediaTrackSettings",
    "MidiAccess",
    "MidiInput",
    "MidiInputMap",
    "MidiMessageEvent",
    "MidiOptions",
    "MidiOutput",
    "MidiOutputMap",
    "MidiPort",
    "MidiPortConnectionState",
    "MidiPortDeviceState",
    "MessageEvent",
    "MessagePort",
    "Navigator",
    "Response",
    "Storage",
    "Window",
] }

[dev-dependencies]
serde_json = { workspace = true }
shoop_session = { path = "../shoop_session" }
tempfile = { workspace = true }

[lints]
workspace = true
