[package]
name = "cxx_qt_lib_shoop"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
cxx = "1.0"
tempfile = "3.2"
tar = "0.4"
glob = "0.3"
dunce = "1.0"
anyhow = "1.0"
ctor = "0.2"
regex = "1"
log = "0.4"
macros = { path = "../macros" }
common = { path = "../common" }
cxx-qt = "0.7"
cxx-qt-lib = { version = "0.7", features = ["full"] }
once_cell = "1.21"
crashhandling = { path = "../crashhandling" }
serde_json = "1.0"

[build-dependencies]
cxx-qt-build = "0.7"
macros = { path = "../macros" }

[features]
# Dummy build to build dependencies only
prebuild = ["macros/prebuild",
            "common/prebuild",
            "crashhandling/prebuild"]

