[package]
name = "shoop_tracing"
version.workspace = true
edition = "2021"

[lib]

[dependencies]
assert_no_alloc = { workspace = true }
ctor = { workspace = true }
tracy-client = { workspace = true, optional = true }
tracy-client-sys = { workspace = true, optional = true }

[dev-dependencies]
shoop_wasm_test_support = { path = "../shoop_wasm_test_support" }

[lints]
workspace = true

[features]
default = ["tracy"]
prebuild = []
tracy = ["dep:tracy-client", "dep:tracy-client-sys"]
