name: Install Qoverage
description: Install Qoverage, for now using a direct link to its Github pre-release.

runs:
  using: "composite"
  steps:
  - name: run
    shell: wrap-shell {0}
    run: |
      $PYTHON -m pip install pipx
      $PYTHON -m pipx install --force qoverage