name: Install Qoverage
description: Install the latest Qoverage dev build from git.

inputs:
  python_command:
    type: string
    default: python3
  pip_install_extra_args:
    required: false
    type: string

runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v3
    with:
      repository: SanderVocke/qoverage
      ref: master
      path: qoverage

  - name: Build and install
    shell: bash
    run: |
      cd qoverage
      ${{ inputs.python_command }} -m build -w
      ${{ inputs.python_command }} -m pip install dist/*.whl ${{ inputs.pip_install_extra_args }}
