name: Install Qoverage
description: Install Qoverage, for now using a direct link to its Github pre-release.

runs:
  using: "composite"
  steps:
  - name: run
    shell: bash
    run: |
      pipx install --force qoverage