[package]
name = "shoop_rs_common"
version = "0.2.0"
authors = [
    "Sander Vocke <sandervocke@gmail.com>"
]
edition = "2021"
license = "TODO"

[lib]

[dependencies]

[build-dependencies]
bindgen = "0.69"