name: Build Base
description: Do a basic Cargo build in the checked out repository

inputs:
  variant_name:
    required: true
    type: string
  python:
    required: false
    type: string
    default: python3
  prepend_build_cmd:
    required: false
    type: string
  release_build:
    required: true
    type: string


outputs:
  build_dir:
    value: ${{ steps.build.outputs.build_dir }}
  source_dir:
    value: ${{ steps.build.outputs.source_dir }}

runs:
  using: "composite"
  steps:

  - name: Release build flags
    if: ${{ inputs.release_build == 'true' }}
    shell: wrap-shell {0}
    run: |
       echo "CARGO_BUILD_FLAGS=--release" | tee -a GITHUB_ENV

  - name: Debug build flags
    if: ${{ inputs.release_build != 'true' }}
    shell: wrap-shell {0}
    run: |
       echo "CARGO_BUILD_FLAGS=" | tee -a GITHUB_ENV

  - name: Build base (${{ inputs.variant_name }})
    shell: wrap-shell {0}
    id: build
    run: |
      ${{ inputs.prepend_build_cmd }} PYTHON=${{ inputs.python }} cargo build -vv ${{ env.CARGO_BUILD_FLAGS }}
      echo "source_dir=$(pwd)" | tee -a $GITHUB_OUTPUT
      echo "build_dir=$(realpath target/release)" | tee -a $GITHUB_OUTPUT


