name: Build Base
description: Do a basic Cargo build in the checked out repository

runs:
  using: "composite"
  steps:

  - name: Rust cache
    uses: Swatinem/rust-cache@v2
    if: runner.os != 'Windows'
    with:
        prefix-key: v2
        env-vars: "CARGO CC CFLAGS CXX CMAKE RUST PYO3"

  - name: Build dependencies
    if: always()
    shell: wrap-shell {0}
    run: |
      # FIXME REMOVE
      rm -f /usr/bin/link.exe || true
      echo "link binary: $(which link)"
      cargo build --features "shoopdaloop/prebuild packaging/prebuild" ${CARGO_BUILD_FLAGS}

  - name: Build main packages
    if: always()
    shell: wrap-shell {0}
    run: |
      cargo build -vv ${CARGO_BUILD_FLAGS}
  
  - name: Build test code
    if: always()
    shell: wrap-shell {0}
    run: |
      cargo test -vv --no-run ${CARGO_BUILD_FLAGS}
