name: Build Base
description: Do a build in the checked out repository

inputs:
  release_build:
    description: "if true, does a release build. Otherwise, a debug build."
    default: 'false'
  allow_warnings:
    description: "if false, warnings become errors"
    default: true
  check_format:
    description: "if true, fails on rustformat changes"
    default: false

runs:
  using: "composite"
  steps:

  - name: Rust cache
    uses: Swatinem/rust-cache@v2
    if: runner.os != 'Windows'
    with:
        prefix-key: v4
        env-vars: "CARGO CC CFLAGS CXX CMAKE RUST PYO3"
  
  - name: Set release flags
    if: always() && inputs.release_build == 'true'
    shell: wrap-shell {0}
    run: |
        echo "CARGO_BUILD_FLAGS=--release" | tee -a $GITHUB_ENV
        echo "BUILD_ENV_FILE=./build/build-env-release.sh" | tee -a $GITHUB_ENV

  - name: Set debug flags
    if: always() && inputs.release_build != 'true'
    shell: wrap-shell {0}
    run: |
        echo "CARGO_BUILD_FLAGS=" | tee -a $GITHUB_ENV
        echo "BUILD_ENV_FILE=./build/build-env-debug.sh" | tee -a $GITHUB_ENV

  - name: Setup build env and build vcpkg packages
    if: always()
    shell: wrap-shell {0}
    run: |
      set -x
      ${PYTHON} scripts/vcpkg_prebuild.py --vcpkg-args=--clean-after-build 2>&1 | tee vcpkg_build_output.txt
      echo ""
      echo "Build env file ${BUILD_ENV_FILE}" contents:
      cat ${BUILD_ENV_FILE}
      rm -rf ${VCPKG_ROOT}/buildtrees

  - name: Check rustfmt
    if: always() && inputs.check_format == 'true'
    shell: wrap-shell {0}
    run: |
      cargo fmt --all --check

  - name: Build Cargo dependencies
    if: always()
    shell: wrap-shell {0}
    run: |
      set -x
      . ${BUILD_ENV_FILE}
      echo "cargo: $(which cargo)"
      cargo build --features "shoopdaloop/prebuild packaging/prebuild py_env/prebuild backend/prebuild backend_bindings/prebuild macros/prebuild common/prebuild config/prebuild frontend/prebuild py_env/prebuild py_prepare/prebuild" ${CARGO_BUILD_FLAGS}

  - name: Extra flags for main build
    if: always() && inputs.allow_warnings != 'true'
    shell: wrap-shell {0}
    run: |
      echo "RUSTFLAGS=-Dwarnings" | tee -a $GITHUB_ENV

  - name: Build main packages
    if: always()
    shell: wrap-shell {0}
    run: |
      set -x
      . ${BUILD_ENV_FILE}
      cargo build -vv ${CARGO_BUILD_FLAGS}
  
  - name: Build test code
    if: always()
    shell: wrap-shell {0}
    run: |
      set -x
      . ${BUILD_ENV_FILE}
      cargo test -vv --no-run ${CARGO_BUILD_FLAGS}
