name: Build Base
description: Do a basic Cargo build in the checked out repository

inputs:
  variant_name:
    required: true
    type: string
  python:
    required: false
    type: string
    default: python3
  prepend_build_cmd:
    required: false
    type: string

outputs:
  build_dir:
    value: ${{ steps.build.outputs.build_dir }}
  source_dir:
    value: ${{ steps.build.outputs.source_dir }}

runs:
  using: "composite"
  steps:

  - name: Build base (${{ inputs.variant_name }})
    shell: wrap-shell {0}
    id: build
    # TODO: release part should not always be here
    run: |
      ${{ inputs.prepend_build_cmd }} PYTHON=${{ inputs.python }} cargo build -vv --release
      echo "source_dir=$(pwd)" | tee -a $GITHUB_OUTPUT
      echo "build_dir=$(realpath target/release)" | tee -a $GITHUB_OUTPUT


