name: Build Base
description: Do a basic Cargo build in the checked out repository

runs:
  using: "composite"
  steps:

  - name: Rust cache
    uses: Swatinem/rust-cache@v2

  - name: Build
    if: always()
    shell: wrap-shell {0}
    run: |
      cargo build ${CARGO_BUILD_FLAGS}
      cargo test --no-run ${CARGO_BUILD_FLAGS}
