name: Build Base
description: Do a basic Cargo build in the checked out repository

inputs:
  variant_name:
    required: true
    type: string
  python:
    required: false
    type: string
    default: python3
  prepend_build_cmd:
    required: false
    type: string
  release_build:
    required: true
    type: string

runs:
  using: "composite"
  steps:

  - name: Build release (${{ inputs.variant_name }})
    if: ${{ inputs.release_build == 'true' }}
    shell: wrap-shell {0}
    run: |
      ${{ inputs.prepend_build_cmd }} PYTHON=${{ inputs.python }} cargo build -vv --release
      ln -s target/release rust_build_out
  
  - name: Build debug (${{ inputs.variant_name }})
    if: ${{ inputs.release_build != 'true' }}
    shell: wrap-shell {0}
    run: |
      ${{ inputs.prepend_build_cmd }} PYTHON=${{ inputs.python }} cargo build -vv
      ln -s target/debug rust_build_out
      


