name: Build Base
description: Do a basic Cargo build in the checked out repository

runs:
  using: "composite"
  steps:

  - name: Rust cache
    uses: Swatinem/rust-cache@v2

  - name: Install build-deps
    if: always()
    shell: wrap-shell {0}
    run: cargo install --git https://github.com/romac/cargo-build-deps.git

  - name: Build dependencies
    if: always()
    shell: wrap-shell {0}
    run: |
      cargo build-deps ${CARGO_BUILD_FLAGS}

  - name: Build
    if: always()
    shell: wrap-shell {0}
    run: |
      cargo build -vv ${CARGO_BUILD_FLAGS}
  
  - name: Build test code
    if: always()
    shell: wrap-shell {0}
    run: |
      cargo test --no-run ${CARGO_BUILD_FLAGS}
