[package]
name = "shoopdaloop"
version = "0.0.0"
description = "Live looping application with DAW elements"
authors = [
    "Sander Vocke <sandervocke@gmail.com>"
]
edition = "2021"
license-file = "LICENSE"

[lib]

[[bin]]
name = "print_shoopdaloop_out_dir"
path = "src/bin/print_shoopdaloop_out_dir.rs"

[dependencies]
pyo3 = "0.22"
glob = "0.3"
anyhow = "1.0"
regex = "1.10"
copy_dir = "0.1"
clap = { version = "4.5", features = ["derive"] }
frontend = { path = "../frontend" }
backend_bindings = { path = "../backend_bindings" }
common = { path = "../common" }
py_env = { path = "../py_env" }
config = { path = "../config" }
log = "0.4"
ctor = "0.2"
toml = "0.8"
serde = "1.0"

[build-dependencies]
glob = "0.3"
copy_dir = "0.1"
anyhow = "1.0"
backend = { path = "../backend" }
common = { path = "../common" }
config = { path = "../config" }
toml = "0.8"
serde = "1.0"
log = "0.4"
ctor = "0.2"

[features]
# Dummy build to build dependencies only
prebuild = ["frontend/prebuild",
            "backend_bindings/prebuild",
            "backend/prebuild",
            "py_env/prebuild",
            "common/prebuild",
            "py_env/prebuild"]