[package]
name = "shoopdaloop"
version = "0.0.0"
description = "Live looping application with DAW elements"
authors = [
    "Sander Vocke <sandervocke@gmail.com>"
]
edition = "2021"
license-file = "LICENSE"

[lib]

[[bin]]
name = "print_shoopdaloop_out_dir"
path = "src/bin/print_shoopdaloop_out_dir.rs"

[dependencies]
frontend = { path = "../frontend" }
shoop_engine = { path = "../shoop_engine", features = ["cpal", "midir"] }
shoop_plugin_protocol = { path = "../shoop_plugin_protocol" }
shoop_settings = { path = "../shoop_settings", features = ["legacy"] }
common = { path = "../common" }
config = { path = "../config" }
crashhandling = { path = "../crashhandling" }
cxx_qt_lib_shoop = { path = "../cxx_qt_lib_shoop" }

glob = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true }
copy_dir = { workspace = true }
clap = { workspace = true, features = ["derive"] }
log = { workspace = true }
ctor = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
cxx-qt = { workspace = true }
cxx-qt-lib = { workspace = true, features = ["full"] }
assert_no_alloc = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
libc = { workspace = true }

[lints]
workspace = true

[build-dependencies]
common = { path = "../common" }
config = { path = "../config" }
cxx-qt-build = { workspace = true }


glob = { workspace = true }
copy_dir = { workspace = true }
anyhow = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
ctor = { workspace = true }

[features]
# Dummy build to build dependencies only
prebuild = ["frontend/prebuild",
            "shoop_engine/prebuild",
            "common/prebuild",
            "config/prebuild",
            "crashhandling/prebuild",
            "cxx_qt_lib_shoop/prebuild"]