[package]
name = "shoopdaloop"
version = "0.1.2"
description = "Live looping application with DAW elements"
authors = [
    "Sander Vocke <sandervocke@gmail.com>"
]
edition = "2021"
license-file = "LICENSE"

[lib]

[[bin]]
name = "shoopdaloop_dev"
path = "src/bin/shoopdaloop_dev.rs"

[dependencies]
pyo3 = "0.22"
glob = "0.3"
anyhow = "1.0"
regex = "1.10"
copy_dir = "0.1"
clap = { version = "4.5", features = ["derive"] }
frontend = { path = "../frontend" }
backend_bindings = { path = "../backend_bindings" }

[build-dependencies]
glob = "0.3"
copy_dir = "0.1"
anyhow = "1.0"
backend = { path = "../backend" }
py_env = { path = "../py_env" }