[package]
name = "shoopdaloop"
version = "0.0.0"
description = "Live looping application with DAW elements"
authors = [
    "Sander Vocke <sandervocke@gmail.com>"
]
edition = "2021"
license-file = "LICENSE"

[lib]

[[bin]]
name = "print_shoopdaloop_out_dir"
path = "src/bin/print_shoopdaloop_out_dir.rs"

[dependencies]
frontend = { path = "../frontend" }
backend_bindings = { path = "../backend_bindings" }
common = { path = "../common" }
config = { path = "../config" }
crashhandling = { path = "../crashhandling" }
cxx_qt_lib_shoop = { path = "../cxx_qt_lib_shoop" }

glob = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true }
copy_dir = { workspace = true }
clap = { workspace = true, features = ["derive"] }
log = { workspace = true }
ctor = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
cxx-qt-lib = { workspace = true, features = ["full"] }

[build-dependencies]
backend = { path = "../backend" }
common = { path = "../common" }
config = { path = "../config" }

glob = { workspace = true }
copy_dir = { workspace = true }
anyhow = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
ctor = { workspace = true }

[features]
# Dummy build to build dependencies only
prebuild = ["frontend/prebuild",
            "backend_bindings/prebuild",
            "backend/prebuild",
            "common/prebuild",
            "crashhandling/prebuild"]