[package]
name = "shoopdaloop"
version = "0.1.2"
description = "Live looping application with DAW elements"
authors = [
    "Sander Vocke <sandervocke@gmail.com>"
]
edition = "2021"
license-file = "LICENSE"

[lib]

[dependencies]
pyo3 = "0.22"
glob = "0.3"
anyhow = "1.0"
regex = "1.10"
copy_dir = "0.1"
frontend = { path = "../frontend" }

[build-dependencies]
glob = "0.3"
cmake = "0.1"
copy_dir = "0.1"
anyhow = "1.0"