name: QML Tests
description: Integration tests at the QML level

inputs:
  variant_name:
    required: true
    type: string
  tee_all_output_to:
    type: string
    default: /dev/null
  macos_rpath_patch:
    type: boolean
    required: false
    default: false

runs:
  using: "composite"
  steps:
  - name: prepare
    if: always()
    shell: wrap-shell {0}
    run: |
      mkdir -p reports
      echo "RESULTS_XML=reports/qml_test_${{ inputs.variant_name }}_results.xml" | tee -a $GITHUB_ENV

  - name: QML test (${{ inputs.variant_name }})
    if: always()
    shell: wrap-shell {0}
    run: >
      QT_ASSUME_STDERR_HAS_CONSOLE=1
      ${{ env.RUN_CMD_PREFIX }}
      ${{ env.SHOOPDALOOP_COMMAND }} --qml-self-test
      --
      --junit ${{ env.RESULTS_XML }}
      2>&1 | tee ${{ inputs.tee_all_output_to }}
  
  - name: Report results filename
    shell: wrap-shell {0}
    if: always()
    run: |
      echo "QML test results file: $(ls -la ${{ env.RESULTS_XML }})"
  
  - name: Publish QML Test Report
    if: always()
    uses: mikepenz/action-junit-report@v3
    with:
      report_paths: ${{ env.RESULTS_XML }}
      include_passed: false
      check_name: 'QML test (${{ inputs.variant_name }})'
      annotate_only: true

