ignore:
  - ".github"
  - "docs"
  - "dist"
  - "distribution"
  - "scripts"
  - "build"
  - "src/qml/third_party"
  - "portable"

fixes:
  - "/__w/shoopdaloop/shoopdaloop/::"

comment:
  layout: "header, diff, flags, components"

component_management:
  individual_components:
    - component_id: rust
      name: Rust
      paths:
        - "src/rust/**"

coverage:
  status:
    project:
      default:
        branches:
          - master
        informational: true
    patch:
      default:
        branches:
          - master
        informational: true
