[package]
name = "shoop_backend"
edition = "2021"

[features]
default = []
native-drivers = ["shoop_engine/app_backend"]

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
shoop_app_api = { path = "../shoop_app_api" }
shoop_engine = { path = "../shoop_engine" }

[dev-dependencies]
assert_no_alloc = { workspace = true }

[lints]
workspace = true
