[package]
name = "shoop_backend"
version.workspace = true
edition = "2021"

[features]
default = []
native-drivers = ["shoop_engine/native_audio_backend"]
native-fx = ["native-drivers", "shoop_engine/carla", "dep:shoop_plugin_protocol"]

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
shoop_app_api = { path = "../shoop_app_api" }
shoop_engine = { path = "../shoop_engine" }
shoop_plugin_protocol = { path = "../shoop_plugin_protocol", optional = true }
shoop_settings = { path = "../shoop_settings" }

[dev-dependencies]
tracy-nextest-capture = { workspace = true }
assert_no_alloc = { workspace = true }

[lints]
workspace = true
