[package]
name = "shoop_backend"
version.workspace = true
edition = "2021"

[package.metadata.shoop-wasm-test]
enabled = true
browser-feature = "wasm-test-browser"

[features]
default = []
native-drivers = ["shoop_engine/native_audio_backend"]
native-fx = ["native-drivers", "shoop_engine/carla", "dep:shoop_plugin_protocol"]
wasm-test-browser = ["shoop_wasm_test_support/wasm-test-browser"]

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
shoop_app_api = { path = "../shoop_app_api" }
shoop_engine = { path = "../shoop_engine" }
shoop_latency = { path = "../shoop_latency" }
shoop_plugin_protocol = { path = "../shoop_plugin_protocol", optional = true }
shoop_settings = { path = "../shoop_settings" }

[dev-dependencies]
assert_no_alloc = { workspace = true }
serde_json = { workspace = true }
shoop_wasm_test_support = { path = "../shoop_wasm_test_support" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "=0.3.77"

[lints]
workspace = true
