#!/bin/sh

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
. ${SCRIPT_DIR}/env.sh

if [ ! -f $SCRIPT_DIR/cargo-nextest ]; then
    echo "Rust tests were not bundled in this app." >&2
    exit 1;
else
    $SCRIPT_DIR/cargo-nextest nextest run --archive-file $SCRIPT_DIR/nextest-archive.tar.zst $@
fi