qml_dir = "$ROOT/qml"
lua_dir = "$ROOT/lua"
resource_dir = "$ROOT/resources"
schemas_dir = "$ROOT/session_schemas"
pythonpaths = ["$ROOT/lib/python", "$ROOT/lib/python/site-packages", "$ROOT/lib/python/lib-dynload"]
dynlibpaths = ["$ROOT/lib"]