# For format-checking the code.

runs:
  using: "composite"
  steps:
  - name: Prepare Rust
    if: always()
    uses: actions-rust-lang/setup-rust-toolchain@v1
    with:
      toolchain: nightly
      components: rustfmt
      cache: false
      rustflags: ""
  - name: Check format
    if: always()
    shell: bash
    run: cargo fmt --all --check