[package]
name = "shoop_rs_macros"
version = "0.2.0"
authors = [
    "Sander Vocke <sandervocke@gmail.com>"
]
edition = "2021"
license = "TODO"

[lib]
proc-macro = true

[dependencies]
quote = "*"
syn = { version = "*", features = ["full"] }