name: prepare_manylinux_2_28
description: Prepare manylinux for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - name: Manylinux prep
    shell: bash
    run: |
      # Skip if already done (local act builds)
      if [ -f /manylinux_prepared ]; then
        exit 0
      fi

      # Python alias
      ln -s /usr/local/bin/python3.8 /usr/local/bin/python
      ln -s /usr/local/bin/python3.8 /usr/local/bin/python3
      echo "export PATH=\"\$PATH:$(find /opt/_internal -name "cpython-3.8.*")/bin\"" >> $HOME/.bashrc

      # Official packages needed
      dnf -y install ninja-build libsndfile libsamplerate gcc-toolset-12-libasan-devel perl-Time-HiRes perl-Capture-Tiny

      # Build and install Jack
      git clone https://github.com/jackaudio/jack2.git
      cd jack2
      ./waf configure
      ./waf
      ./waf install

      # Install Boost
      curl -L https://boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.gz --output boost.tar.gz
      tar -xzf boost.tar.gz
      cp -r boost_1_82_0/boost /usr/include/boost
      curl -L https://github.com/nlohmann/json/releases/download/v3.11.2/include.zip --output include.zip
      unzip include.zip
      cp -r include/* /usr/include/

      # Build and install lcov
      curl -L https://github.com/linux-test-project/lcov/releases/download/v2.0/lcov-2.0.tar.gz --output lcov-2.0.tar.gz
      tar -xzf lcov-2.0.tar.gz
      pushd lcov-2.0
      make install
      popd

      touch /manylinux_prepared