name: prepare_manylinux_2_28
description: Prepare manylinux for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - name: Manylinux prep
    shell: bash
    run: |
      # Skip if already done (local act builds)
      if [ -f /manylinux_prepared ]; then
        exit 0
      fi

      # Python alias
      ln -s /usr/local/bin/python3.8 /usr/local/bin/python
      ln -s /usr/local/bin/python3.8 /usr/local/bin/python3
      echo "export PATH=\"\$PATH:$(find /opt/_internal -name "cpython-3.8.*")/bin\"" >> $HOME/.bashrc

      # Official packages needed
      dnf -y install ninja-build libsndfile libsamplerate libasan8 gcc-toolset-12-libasan-devel.x86_64 perl-Time-HiRes perl-Capture-Tiny perl-Module-Load-Conditional perl-DateTime perl-JSON perl-JSON-XS

      # libasan hacks, not sure why needed.
      # the libasan from the gcc-toolset-12 package is reported as having an invalid ELF header.
      # the libasan_preinit.so is needed though.
      # libasan.so.8 from the libasan8 package does seem to work.
      rm -f /opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/libasan.so
      ln -s /lib64/libasan.so.8 /lib64/libasan.so

      # Build and install Jack
      git clone https://github.com/jackaudio/jack2.git
      cd jack2
      ./waf configure
      ./waf
      ./waf install

      # Install Boost
      curl -L https://boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.gz --output boost.tar.gz
      tar -xzf boost.tar.gz
      cp -r boost_1_82_0/boost /usr/include/boost
      curl -L https://github.com/nlohmann/json/releases/download/v3.11.2/include.zip --output include.zip
      unzip include.zip
      cp -r include/* /usr/include/

      # Build and install lcov
      curl -L https://github.com/linux-test-project/lcov/releases/download/v2.0/lcov-2.0.tar.gz --output lcov-2.0.tar.gz
      tar -xzf lcov-2.0.tar.gz
      pushd lcov-2.0
      make install
      popd

      touch /manylinux_prepared