name: post_build_windows
description: Steps after building wheel for Windows

inputs:
  wheel:
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - name: Dummy
    shell: bash
    run: |
      echo "Dummy step"
      