name: post_build_windows
description: Steps after building wheel for Windows

inputs:
  wheel:
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - name: Delvewheel
    shell: sh wrap-shell.sh {0}
    run: |
      python -m pip install delvewheel
      delvewheel show ${{ inputs.wheel }}
  - name: Passthrough
    id: passthrough
    shell: sh wrap-shell.sh {0}
    run: |
      mkdir -p final_wheel
      cp dist/*.whl final_wheel/
      