name: QML Tests
description: Integration tests at the QML level

inputs:
  variant_name:
    required: true
    type: string
  run_cmd_prefix:
    type: string
    description: "Command-line prefix to use when running the test runner"
  root_path:
    type: string
    required: true
  python_command:
    type: string
    default: python3
  tee_all_output_to:
    type: string
    default: /dev/null

runs:
  using: "composite"
  steps:
  - name: prepare
    shell: bash
    run: |
      mkdir -p reports
      echo "results_xml=reports/qml_test_${{ inputs.variant_name }}_results.xml" | tee -a $GITHUB_ENV

  - name: QML test (${{ inputs.variant_name }})
    shell: bash
    run: |
      ASAN_OPTIONS=detect_leaks=0,new_delete_type_mismatch=0 QT_QPA_PLATFORM=vnc ${{ inputs.run_cmd_prefix }} ${{ inputs.python_command }} ${{ inputs.root_path }}/run_qml_tests.py -input ${{ inputs.root_path }}/lib/qml/test/tst_TwoLoops.qml -o ${{ env.results_xml }},junitxml 2>&1 | tee ${{ inputs.tee_all_output_to }}
      echo "QML test results file: $(ls -la ${{ env.results_xml }})"
  
  - name: Publish QML Test Report
    if: ${{ !env.ACT }}
    uses: mikepenz/action-junit-report@v3
    with:
      report_paths: ${{ env.results_xml }}
      detailed_summary: true
      include_passed: true
      check_name: 'QML test (${{ inputs.variant_name }})'

