[package]
name = "qt_header_bindings"
edition = "2021"

[lib]

[dependencies]
enum-iterator = { workspace = true }

[build-dependencies]
bindgen = { workspace = true }
anyhow = { workspace = true }
syn = { workspace = true }
prettyplease = { workspace = true }

[features]
# Dummy build to build dependencies only
prebuild = []