[package]
name = "common"
edition = "2021"

[lib]

[dependencies]
log = { workspace = true }
colored = { workspace = true }
humantime = { workspace = true }
fern = { workspace = true, features = ["colored"] }
lazy_static = { workspace = true }
anyhow = { workspace = true }
ctor = { workspace = true }
walkdir = { workspace = true }

[build-dependencies]
toml = { workspace = true }