[package]
name = "macros"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = { workspace = true }
syn = { workspace = true, features = ["full"] }

[features]
# Dummy build to build dependencies only
prebuild = []