name: prepare_build_linux
description: Prepare Linux for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - name: Shell steps
    shell: wrap-shell {0}
    run: |
      python3 -m pip install --upgrade pip build auditwheel patchelf