name: prepare_build_linux
description: Prepare Linux for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - name: Shell steps
    shell: wrap-shell {0}
    run: |
      $PIP install --upgrade pip build auditwheel patchelf
      $PIP install -r build_python_requirements.txt