name: prepare_build_linux
description: Prepare Linux for building Shoopdaloop

runs:
  using: "composite"
  steps:
  - name: Shell steps
    if: always()
    shell: wrap-shell {0}
    run: |
      $PIP install --upgrade pip build patchelf toml jinja2
      echo "RUSTFLAGS=-C linker=gcc" | tee -a $GITHUB_ENV