name: App run test
description: Integration test which runs the full ShoopDaLoop app.

inputs:
  variant_name:
    required: true
    type: string
  root_path:
    type: string
    required: true
  qt_qpa_platform:
    type: string
    default: vnc

runs:
  using: "composite"
  steps:
  - name: run app (${{ inputs.variant_name }})
    if: always()
    shell: wrap-shell {0}
    run: >
        ${{ env.RUN_COMMAND_PREFIX }}
        ${{ env.SHOOPDALOOP_COMMAND }} --quit-after=40 -b dummy --monkey-tester


