name: App run test
description: Integration test which runs the full ShoopDaLoop app.

inputs:
  variant_name:
    required: true
    type: string
  root_path:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - name: run app
    if: always()
    shell: wrap-shell {0}
    run: >
        ${{ env.RUN_COMMAND_PREFIX }}
        ${{ env.COMMAND_SHOOPDALOOP }} --quit-after=40 -b dummy --monkey-tester


