name: Back-end Tests
description: Unit tests for libshoopdaloop

inputs:
  variant_name:
    required: true
    type: string
  run_cmd_prefix:
    type: string
    description: "Command-line prefix to use when running the test runner"
  test_runner_dir:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - name: prepare
    shell: bash
    run: |
      mkdir -p reports
      echo "results_xml=reports/test_runner_${{ inputs.variant_name }}_results.xml" | tee -a $GITHUB_ENV

  - name: test_runner (${{ inputs.variant_name }})
    shell: bash
    run: |
      mkdir -p reports
      ${{ inputs.run_cmd_prefix }} ${{ inputs.test_runner_dir }}/test_runner --reporter junit --out ${{ env.results_xml }}
      echo "Back-end test results file: $(ls -la ${{ env.results_xml }})"
  
  - name: Publish Back-end Test Report
    if: ${{ !env.ACT }} && (success() || failure())
    uses: mikepenz/action-junit-report@v3
    with:
      report_paths: ${{ env.results_xml }}
      detailed_summary: true
      include_passed: true
      check_name: 'backend test (${{ inputs.variant_name }})'

