name: Back-end Tests
description: Unit tests for libshoopdaloop

inputs:
  variant_name:
    required: true
    type: string
  test_runner:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - name: prepare
    shell: wrap-shell {0}
    run: |
      mkdir -p reports
      echo "results_xml=reports/test_runner_${{ inputs.variant_name }}_results.xml" | tee -a $GITHUB_ENV

  - name: Expand prefix for Mac
    shell: wrap-shell {0}
    id: runcmdprefix
    run: |
      if [[ "$RUNNER_OS" == "macOS" ]]; then
        echo "RUN_CMD_PREFIX=DYLD_FALLBACK_LIBRARY_PATH=$(dirname ${{ inputs.test_runner }}) $RUN_CMD_PREFIX" | tee -a $GITHUB_ENV
      fi

  - name: test_runner (${{ inputs.variant_name }})
    shell: wrap-shell {0}
    run: |
      mkdir -p reports
      ${{ env.RUN_CMD_PREFIX }} ${{ inputs.test_runner }} -r JUnit -o ${{ env.results_xml }}
      echo "Back-end test results file: $(ls -la ${{ env.results_xml }})"

  - name: Publish Back-end Test Report
    if: ${{ !env.ACT && (success() || failure()) }}
    uses: mikepenz/action-junit-report@v3
    with:
      report_paths: ${{ env.results_xml }}
      include_passed: false
      check_name: 'backend test (${{ inputs.variant_name }})'
      annotate_only: true

