name: Back-end Tests
description: Unit tests for libshoopdaloop_backend

runs:
  using: "composite"
  steps:
  - name: prepare
    if: always()
    shell: wrap-shell {0}
    run: |
      mkdir -p reports
      echo "results_xml=reports/backend_tests_results.xml" | tee -a $GITHUB_ENV

  - name: Backend tests
    if: always()
    shell: wrap-shell {0}
    run: |
      set -x
      mkdir -p reports
      ${{ env.RUN_CMD_PREFIX }} ${{ env.COMMAND_TEST_BACKEND }} -r JUnit -o ${{ env.results_xml }}
      echo "Back-end test results file: $(ls -la ${{ env.results_xml }})"

  - name: Publish Back-end Test Report
    if: always()
    uses: mikepenz/action-junit-report@v3
    with:
      report_paths: ${{ env.results_xml }}
      include_passed: false
      check_name: 'backend tests'
      annotate_only: true

