[package]
name = "frontend"
edition = "2021"
links = "frontend"

[lib]
crate-type = ["lib"]

[dependencies]
cxx = "1.0"
tempfile = "3.2"
tar = "0.4"
glob = "0.3"
dunce = "1.0"
anyhow = "1.0"
ctor = "0.2"
regex = "1"
log = "0.4"
macros = { path = "../macros" }
backend_bindings = { path = "../backend_bindings" }
common = { path = "../common" }
cxx-qt = "0.7"
cxx-qt-lib = { version = "0.7", features = ["full"] }

[build-dependencies]
cxx-qt-build = "0.7.0"
macros = { path = "../macros" }

[features]
# Dummy build to build dependencies only
prebuild = ["macros/prebuild",
            "backend_bindings/prebuild",
            "common/prebuild"]


            [profile.dev.package."cxx-qt-build"]
debug = true

[target.'cfg(windows)'.patch.crates-io]
cxx-qt =  { git = "https://github.com/SanderVocke/cxx-qt.git", branch = "win_dbg", package = "cxx-qt" }
qt-build-utils = { git = "https://github.com/SanderVocke/cxx-qt.git", branch = "win_dbg", package = "qt-build-utils" }
cxx-qt-build = { git = "https://github.com/SanderVocke/cxx-qt.git", branch = "win_dbg", package = "cxx-qt-build" }
cxx-qt-gen = { git = "https://github.com/SanderVocke/cxx-qt.git", branch = "win_dbg", package = "cxx-qt-gen" }
cxx-qt-lib = { git = "https://github.com/SanderVocke/cxx-qt.git", branch = "win_dbg", package = "cxx-qt-lib" }
cxx-qt-lib-extras = { git = "https://github.com/SanderVocke/cxx-qt.git", branch = "win_dbg", package = "cxx-qt-lib-extras" }
cxx-qt-macro = { git = "https://github.com/SanderVocke/cxx-qt.git", branch = "win_dbg", package = "cxx-qt-macro" }