[package]
name = "frontend"
edition = "2021"
links = "frontend"

[lib]
crate-type = ["lib"]

[dependencies]
macros = { path = "../macros" }
common = { path = "../common" }
shoop_engine = { path = "../shoop_engine", features = ["app_backend"] }
crashhandling = { path = "../crashhandling" }
config = { path = "../config" }
cxx_qt_lib_shoop = { path = "../cxx_qt_lib_shoop" }
egui-cxx-qt = { path = "../../../third_party/egui-cxx-qt" }
midi_processing = { path = "../midi_processing" }
qt_header_bindings = { path = "../qt_header_bindings"}

directories = { workspace = true }
cxx = { workspace = true }
tempfile = { workspace = true }
tar = { workspace = true }
glob = { workspace = true }
dunce = { workspace = true }
anyhow = { workspace = true }
ctor = { workspace = true }
regex = { workspace = true }
log = { workspace = true }
cxx-qt = { workspace = true }
cxx-qt-lib = { workspace = true, features = ["full"] }
once_cell = { workspace = true }
serde_json = { workspace = true }
quick-xml = { workspace = true, features = ["serialize"] }
serde = { workspace = true }
sndfile = { workspace = true }
json = { workspace = true }
midly = { workspace = true }
mlua = { workspace = true }
itertools = { workspace = true }
enum-iterator = { workspace = true }
num_enum = { workspace = true }
jsonschema = { workspace = true }
rodio = { workspace = true }

[lints]
workspace = true

[build-dependencies]
macros = { path = "../macros" }

cxx-qt-build = { workspace = true }
egui-cxx-qt-build = { path = "../../../third_party/egui-cxx-qt/crates/egui-cxx-qt-build" }

[features]
# Dummy build to build dependencies only
prebuild = ["macros/prebuild",
            "common/prebuild",
            "shoop_engine/prebuild",
            "crashhandling/prebuild",
            "config/prebuild",
            "cxx_qt_lib_shoop/prebuild",
            "midi_processing/prebuild",
            "qt_header_bindings/prebuild"]

