[package]
name = "frontend"
edition = "2021"
links = "frontend"

[lib]
crate-type = ["lib"]

[dependencies]
macros = { path = "../macros" }
backend_bindings = { path = "../backend_bindings" }
common = { path = "../common" }
crashhandling = { path = "../crashhandling" }
config = { path = "../config" }
shoop_py_wrapped_objects = { path = "../shoop_py_wrapped_objects" }
cxx_qt_lib_shoop = { path = "../cxx_qt_lib_shoop" }
shoop_py_backend = { path = "../shoop_py_backend"}

cxx = { workspace = true }
tempfile = { workspace = true }
tar = { workspace = true }
glob = { workspace = true }
dunce = { workspace = true }
anyhow = { workspace = true }
ctor = { workspace = true }
regex = { workspace = true }
log = { workspace = true }
cxx-qt = { workspace = true }
cxx-qt-lib = { workspace = true, features = ["full"] }
once_cell = { workspace = true }
serde_json = { workspace = true }
quick-xml = { workspace = true, features = ["serialize"] }
serde = { workspace = true }


[build-dependencies]
macros = { path = "../macros" }

cxx-qt-build = { workspace = true }

[features]
# Dummy build to build dependencies only
prebuild = ["macros/prebuild",
            "backend_bindings/prebuild",
            "common/prebuild",
            "shoop_py_wrapped_objects/prebuild",
            "crashhandling/prebuild",
            "config/prebuild",
            "cxx_qt_lib_shoop/prebuild"]

