[package]
name = "frontend"
edition = "2021"
links = "frontend"

[lib]
crate-type = ["lib"]

[dependencies]
cxx = "1.0"
tempfile = "3.2"
tar = "0.4"
glob = "0.3"
dunce = "1.0"
anyhow = "1.0"
ctor = "0.2"
regex = "1"
log = "0.4"
cxx-qt = "0.7.0"
cxx-qt-lib = { version = "0.7.0", features = ["full"] }
macros = { path = "../macros" }
backend_bindings = { path = "../backend_bindings" }
common = { path = "../common" }

[build-dependencies]
cxx-qt-build = "0.7.0"
macros = { path = "../macros" }

[features]
# Dummy build to build dependencies only
prebuild = ["macros/prebuild",
            "backend_bindings/prebuild",
            "common/prebuild"]