[package]
name = "frontend"
edition = "2021"
links = "frontend"

[lib]
crate-type = ["lib"]

[dependencies]
cxx = "1.0"
tempfile = "3.2"
tar = "0.4"
glob = "0.3"
dunce = "1.0"
anyhow = "1.0"
ctor = "0.2"
regex = "1"
log = "0.4"
cxx-qt = { git = "https://github.com/KDAB/cxx-qt.git", rev = "dff128ffebcb0ecf3635d81ee9a95581bc8cd37a" }
cxx-qt-lib = { git = "https://github.com/KDAB/cxx-qt.git", rev = "dff128ffebcb0ecf3635d81ee9a95581bc8cd37a", features = ["full_qt"] }
macros = { path = "../macros" }
backend_bindings = { path = "../backend_bindings" }
common = { path = "../common" }

[build-dependencies]
cxx-qt-build = { git = "https://github.com/KDAB/cxx-qt.git", rev = "dff128ffebcb0ecf3635d81ee9a95581bc8cd37a" }
macros = { path = "../macros" }