[package]
name = "shoop_wasm_runtime_tests"
version.workspace = true
edition = "2021"
publish = false

[package.metadata.shoop-wasm-test]
enabled = true
browser-feature = "wasm-test-browser"

[features]
default = []
wasm-test-browser = []

[dependencies]
shoop_audio_protocol = { path = "../shoop_audio_protocol" }
shoop_wasm_test_support = { path = "../shoop_wasm_test_support" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "=0.2.127"
wasm-bindgen-futures = "=0.4.77"
wasm-bindgen-test = "=0.3.77"

[lints]
workspace = true
