name: Qoverage
description: Run Qoverage.

inputs:
  command_json:
    type: string
  docker_options:
    type: string

runs:
  using: 'docker'
  image: 'docker://sandervocke/qoverage:latest'
  entrypoint: '["/bin/sh", "-c"]'
  args: ${{ fromJSON(github.event.inputs.command_json) }}