[package]
name = "shoop_scripting"
version.workspace = true
edition = "2021"

[dependencies]
anyhow = { workspace = true }
omnilua = { workspace = true }
regex = { workspace = true }
shoop_app_api = { path = "../shoop_app_api" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
midir = { workspace = true }

[dev-dependencies]
tracy-nextest-capture = { workspace = true }

[lints]
workspace = true
