name: Download Qt
description: Download Qt from GitHub release page

inputs:
  url:
    required: false
    type: string
    default: https://github.com/SanderVocke/shoopdaloop/releases/download/qt-6.5.3-1/qt-6.5.3-shoopdaloop.tar.gz

runs:
  using: "composite"
  steps:
    - name: Download and install
      shell: bash
      run: |
        wget ${{ inputs.url }} -o qt.tar.gz
        tar -xzf qt.tar.gz -C /

