[package]
name = "shoop_script_resources"
version.workspace = true
edition = "2021"

[package.metadata.shoop-wasm-test]
enabled = true
browser-feature = "wasm-test-browser"

[features]
default = []
wasm-test-browser = ["shoop_wasm_test_support/wasm-test-browser"]

[dependencies]
serde = { workspace = true, features = ["derive", "rc"] }
sha2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
shoop_wasm_test_support = { path = "../shoop_wasm_test_support" }
tempfile = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tracy-nextest-capture.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "=0.3.77"

[lints]
workspace = true
