name: QML Tests
description: Integration tests at the QML level

inputs:
  dumps_dir:
    type: string

runs:
  using: "composite"
  steps:

  - name: Process dumps
    id: process
    if: always()
    shell: wrap-shell {0}
    run: |
      if [ $(ls ${{ inputs.dumps_dir}} | wc -l) -gt 0 ]; then
        echo "upload=true" | tee -a $GITHUB_OUTPUT
      fi

  - name: Upload dumps
    if: always() && steps.process.outputs.upload
    uses: actions/upload-artifact@v4
    with:
      name: crashdumps_${{ matrix.kind.name }}_${{ github.run_number }}
      path: ${{ inputs.dumps_dir }}

