name: QML Tests
description: Integration tests at the QML level

inputs:
  python:
    type: string
    default: python3
  dumps_dir:
    type: string
  variant:
    type: string

runs:
  using: "composite"
  steps:

  - name: Process dumps (${{ inputs.variant }})
    id: process
    if: ${{ !env.ACT }}
    shell: wrap-shell.sh {0}
    run: |
      if [ $(ls ${{ inputs.dumps_dir}} | wc -l) -gt 0 ]; then
        echo "upload=true" | tee -a $GITHUB_OUTPUT
      fi

  - name: Upload dumps (${{ inputs.variant }})
    if: ${{ !env.ACT && steps.process.outputs.upload }}
    uses: actions/upload-artifact@v4
    with:
      name: crashdumps_${{ matrix.kind.name }}_${{ github.run_number }}
      path: ${{ inputs.dumps_dir }}

