name: Python Tests
description: Unit tests for Python extensions

inputs:
  variant_name:
    required: true
    type: string
  root_path:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - name: prepare
    shell: wrap-shell {0}
    run: |
      mkdir -p reports
      echo "RESULTS_XML=reports/pytest_${{ inputs.variant_name }}_results.xml" | tee -a $GITHUB_ENV

  - name: pytest (${{ inputs.variant_name }})
    shell: wrap-shell {0}
    run: |
      ${{ env.RUN_CMD_PREFIX }} ${{ env.PYTEST }} ${{ inputs.root_path }} --junit-xml=${{ env.RESULTS_XML }}
      echo "Python test results file: $(ls -la ${{ env.RESULTS_XML }})"
  
  - name: Publish Python Test Report
    if: ${{ !env.ACT && (success() || failure()) }}
    uses: mikepenz/action-junit-report@v3
    with:
      report_paths: ${{ env.RESULTS_XML }}
      include_passed: false
      check_name: 'python test (${{ inputs.variant_name }})'
      annotate_only: true

