name: Python Tests
description: Unit tests for Python extensions

runs:
  using: "composite"
  steps:
  - name: prepare
    if: always()
    shell: wrap-shell {0}
    run: |
      mkdir -p reports
      echo "RESULTS_XML=reports/pytest_results.xml" | tee -a $GITHUB_ENV

  - name: pytest
    if: always()
    shell: wrap-shell {0}
    run: |
      ${{ env.RUN_CMD_PREFIX }} ${{ env.COMMAND_TEST_PYTHON }} --junit-xml=${{ env.RESULTS_XML }}
      echo "Python test results file: $(ls -la ${{ env.RESULTS_XML }})"

  - name: Publish Python Test Report
    if: always()
    uses: mikepenz/action-junit-report@v3
    with:
      report_paths: ${{ env.RESULTS_XML }}
      include_passed: false
      check_name: 'python test'
      annotate_only: true

