[package]
name = "shoop_app"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
shoop_app_api = { path = "../shoop_app_api" }
shoop_backend = { path = "../shoop_backend" }
shoop_session = { path = "../shoop_session" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
shoop_scripting = { path = "../shoop_scripting" }

[dev-dependencies]
midir = { workspace = true }

[lints]
workspace = true
