[package]
name = "shoop_app"
version.workspace = true
edition = "2021"

[package.metadata.shoop-wasm-test]
enabled = true
browser-feature = "wasm-test-browser"

[features]
default = []
wasm-test-browser = ["shoop_wasm_test_support/wasm-test-browser"]

[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
shoop_app_api = { path = "../shoop_app_api" }
shoop_backend = { path = "../shoop_backend" }
shoop_session = { path = "../shoop_session" }
shoop_scripting = { path = "../shoop_scripting" }
shoop_script_resources = { path = "../shoop_script_resources" }
tracing = { workspace = true }

[dev-dependencies]
shoop_wasm_test_support = { path = "../shoop_wasm_test_support" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
midir.workspace = true
tempfile.workspace = true
tracy-nextest-capture.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "=0.3.77"

[lints]
workspace = true
