name: Download Qt
description: Download Qt from GitHub release page

inputs:
  url:
    required: false
    type: string
    default: https://github.com/SanderVocke/shoopdaloop/releases/download/qt-6.5.3-1/qt-6.5.3-manylinux_2_28.tar.gz
  dir:
    required: false
    type: string
    default: /

runs:
  using: "composite"
  steps:
    - name: Download and install
      shell: bash
      run: |
        curl -L ${{ inputs.url }} --output qt.tar.gz
        tar -xzf qt.tar.gz -C ${{ inputs.dir }}

