[package]
name = "backend_bindings"
edition = "2021"

[lib]

[dependencies]
common = { path = "../common" }
shoop_engine = { path = "../shoop_engine", features = ["cpal", "midir"] }
num_enum = { workspace = true }
anyhow = { workspace = true }
enum-iterator = { workspace = true }
log = { workspace = true }
ctor = { workspace = true }
jack = { workspace = true }
cpal = { workspace = true }
midir = { workspace = true }


[features]
# Dummy build to build dependencies only
prebuild = []