name: Build Qt
description: Build Qt from sources

inputs:
  force-rebuild:
    required: false
    type: boolean
    default: false
  install:
    required: false
    type: boolean
    default: true
  upload:
    required: false
    type: boolean
    default: false
  cache:
    required: false
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - name: Determine OS version
      id: find_os
      shell: bash
      run: |
        echo "os_version=$(cat /etc/os-release | grep PRETTY_NAME | cut -d'=' -f2 | tr -d '"' | tr -d ' ' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Cache
      if: ${{ inputs.cache == 'true' }}
      id: cache-qt
      uses: actions/cache@v3
      with:
        path: qt.tar.gz
        key: qt-6.5.3-${{ steps.find_os.outputs.os_version }}-6
    
    - if: ${{ inputs.force-rebuild == 'true' || inputs.cache == 'false' || (inputs.cache == 'true' && steps.cache-qt.outputs.cache-hit != 'true') }}
      name: Download Qt sources
      shell: bash
      run: |
        curl -L https://download.qt.io/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz --output qt-everywhere-src-6.5.3.tar.xz
        tar -xf qt-everywhere-src-6.5.3.tar.xz
        mv qt-everywhere-src-6.5.3 qt

    - if: ${{ inputs.force-rebuild == 'true' || inputs.cache == 'false' || (inputs.cache == 'true' && steps.cache-qt.outputs.cache-hit != 'true') }}
      name: Configure Qt
      shell: bash
      run: |
        mkdir qt-build
        cd qt-build
        ../qt/configure -release -submodules qtdeclarative,qtshadertools

    - if: ${{ inputs.force-rebuild == 'true' || inputs.cache == 'false' || (inputs.cache == 'true' && steps.cache-qt.outputs.cache-hit != 'true') }}
      name: Build Qt
      shell: bash
      run: |
        cmake --build qt-build --parallel 4
        DESTDIR=qt-installed cmake --install qt-build
        DESTDIR=/ cmake --install qt-build

    - if: ${{ inputs.force-rebuild == 'true' || inputs.cache == 'false' || (inputs.cache == 'true' && steps.cache-qt.outputs.cache-hit != 'true') }}
      name: Compress Qt for caching
      shell: bash
      run: |
         cd qt-installed
         tar czvf ../qt.tar.gz *
    
    - if: ${{ inputs.upload == 'true' }}
      name: Upload Qt
      uses: actions/upload-artifact@v3
      with:
        name: qt
        path: qt.tar.gz
    
    - if: ${{ inputs.cache == 'true' && steps.cache-qt.outputs.cache-hit == 'true' && inputs.install == 'true' }}
      name: Install Qt from cache
      shell: bash
      run: |
        tar -xzf qt.tar.gz -C /