name: prepare_build
description: Prepare for building Shoopdaloop wheels


inputs:
  variant:
    required: true
    type: string
  wheel:
    required: true
    type: string
  build_dir:
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - name: Post-build linux
    if: ${{ always() && inputs.variant == 'linux' }}
    uses: ./.github/actions/post_build_linux
    with:
      wheel: ${{ inputs.wheel }}
  - name: Post-build MacOS
    if: ${{ always() && inputs.variant == 'macos' }}
    uses: ./.github/actions/post_build_macos
    with:
      wheel: ${{ inputs.wheel }}
  - name: Post-build Windows
    if: ${{ always() && inputs.variant == 'windows' }}
    uses: ./.github/actions/post_build_windows
    with:
      wheel: ${{ inputs.wheel }}
  - name: Store debug info
    if: always()
    shell: wrap-shell {0}
    run: |
      mkdir -p debuginfo
      cp -r ${{ inputs.build_dir }}/breakpad_symbols debuginfo/breakpad_symbols