name: prepare_build
description: Prepare for building Shoopdaloop wheels


inputs:
  variant:
    required: true
    type: string
  build_dir:
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - name: Store debug info
    if: always()
    shell: wrap-shell {0}
    run: |
      mkdir -p debuginfo
      cp -r ${{ inputs.build_dir }}/breakpad_symbols debuginfo/breakpad_symbols