name: Qoverage Instrument
description: instrument the QML sources. Implemented in a very non-flexible way because of what seems like bugs in action input parsing.

inputs:
  strip:
    type: string
  package_path:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - name: run
    shell: bash
    run: |
      ~/.local/bin/qoverage collect --report qoverage-report.xml --files-path ${{ inputs.package_path }} --input qoverage-console-output.log --strip-paths-expr "${{ inputs.strip }}" --report-prefix src/shoopdaloop/ --verbose