name: Qoverage Instrument
description: instrument the QML sources. Implemented in a very non-flexible way because of what seems like bugs in action input parsing.

inputs:
  strip:
    type: string
  package_path:
    type: string
    required: true
  console_output_file:
    type: string
    required: true
  report_file:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - name: run
    shell: sh wrap-shell.sh {0}
    run: |
      ~/.local/bin/qoverage collect --report ${{ inputs.report_file }} --files-path ${{ inputs.package_path }} --input ${{ inputs.console_output_file }} --strip-paths-expr "${{ inputs.strip }}" --report-prefix src/shoopdaloop/