name: Qoverage Instrument
description: instrument the QML sources.

runs:
  using: "composite"
  steps:
  - name: run
    shell: bash
    run: |
      qoverage instrument --glob pip/shoopdaloop/lib/qml/*.qml --in-place --store-intermediates --verbose