name: Qoverage Instrument
description: instrument the QML sources.

inputs:
  package_path:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - name: run
    id: run
    shell: wrap-shell {0}
    run: |
      ~/.local/bin/qoverage instrument --glob "${{ inputs.package_path }}/lib/qml/*.qml" --in-place --store-intermediates
      echo "upload_sources_path=$(realpath ${{ inputs.package_path }}/lib)" | tee -a $GITHUB_OUTPUT
  
  - name: Upload instrumented sources
    uses: actions/upload-artifact@v4
    with:
      name: coverage_instrumented_sources
      path: ${{ steps.run.outputs.upload_sources_path }}