[package]
name = "py_env"
edition = "2021"

[lib]

[[bin]]
name = "print_py_env_out_dir"
path = "src/bin/print_py_env_out_dir.rs"

[dependencies]

[build-dependencies]
glob = "0.3"
copy_dir = "0.1"
anyhow = "1.0"
backend = { path = "../backend" }
walkdir = "2.4"

[features]
# Dummy build to build dependencies only
prebuild = ["backend/prebuild"]