[package]
name = "py_env"
edition = "2021"

[lib]

[[bin]]
name = "print_py_env_out_dir"
path = "src/bin/print_py_env_out_dir.rs"

[dependencies]

[build-dependencies]
backend = { path = "../backend" }
common = { path = "../common" }
py_prepare = { path = "../py_prepare" }

walkdir = { workspace = true }
glob = { workspace = true }
copy_dir = { workspace = true }
anyhow = { workspace = true }

[features]
# Dummy build to build dependencies only
prebuild = ["backend/prebuild", "common/prebuild", "py_prepare/prebuild"]