[profile.dev.package."cxx-qt-build"]
debug = true

[patch.crates-io]
cxx-qt = { path = "C:/Users/User/cxx-qt/crates/cxx-qt" }
qt-build-utils = { path = "C:/Users/User/cxx-qt/crates/qt-build-utils" }
cxx-qt-build = { path = "C:/Users/User/cxx-qt/crates/cxx-qt-build" }
cxx-qt-gen = { path = "C:/Users/User/cxx-qt/crates/cxx-qt-gen" }
cxx-qt-lib = { path = "C:/Users/User/cxx-qt/crates/cxx-qt-lib" }
cxx-qt-lib-extras = { path = "C:/Users/User/cxx-qt/crates/cxx-qt-lib-extras" }
cxx-qt-macro = { path = "C:/Users/User/cxx-qt/crates/cxx-qt-macro" }