[package]
name = "shoop_wasm_test_support"
version.workspace = true
edition = "2021"
publish = false

[package.metadata.shoop-wasm-test]
enabled = true
browser-feature = "wasm-test-browser"

[features]
default = []
wasm-test-browser = []
wasm-test-failure-canary = []

[dependencies]
shoop_test_macros = { path = "../shoop_test_macros" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures = { version = "0.3", features = ["executor"] }
shoop_tracing = { workspace = true, features = ["perfetto"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
shoop_tracing = { workspace = true, features = ["ordinary-web"] }
wasm-bindgen = "=0.2.127"
wasm-bindgen-test = "=0.3.77"

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
