name: Install JACK2
description: Install JACK2

runs:
  using: "composite"
  steps:
  - name: Install JACK2
    id: jack
    shell: wrap-shell {0}
    if: always()
    run: |
      # Skip if already done (local act builds)
      if [ -f _jack2_installed ]; then
        exit 0
      fi

      git clone https://github.com/jackaudio/jack2.git
      cd jack2
      ./waf configure
      ./waf
      ./waf install

      touch _jack2_installed