name: prepare_build
description: Prepare for building Shoopdaloop wheels


inputs:
  variant:
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - name: Prepare manylinux
    if: ${{ inputs.variant == 'manylinux_2_28' }}
    uses: ./.github/actions/prepare_build_manylinux_2_28
  - name: Prepare MacOS
    if: ${{ inputs.variant == 'macos' }}
    uses: ./.github/actions/prepare_build_macos
  - name: Prepare Windows
    if: ${{ inputs.variant == 'windows' }}
    uses: ./.github/actions/prepare_build_windows