name: prepare_build
description: Prepare for building Shoopdaloop wheels


inputs:
  variant:
    required: true
    type: string

outputs:
  prepend_build_cmd:
    description: "Command-line prefix to use when running the apps in the built wheel"
    value: ${{ steps.collect.outputs.prepend_build_cmd }}

runs:
  using: "composite"
  steps:
  - name: Prepare manylinux
    if: ${{ inputs.variant == 'manylinux_2_28' }}
    uses: ./.github/actions/prepare_build_manylinux_2_28
  - name: Prepare MacOS
    if: ${{ inputs.variant == 'macos' }}
    uses: ./.github/actions/prepare_build_macos
  - name: Prepare Windows
    if: ${{ inputs.variant == 'windows' }}
    uses: ./.github/actions/prepare_build_windows
  - name: Collect information
    id: collect
    shell: bash
    run: |
      echo "prepend_build_cmd=$(cat prepend_build_cmd.txt)" | tee -a GITHUB_OUTPUT