[package]
name = "shoop_audio_worklet"
version.workspace = true
edition = "2021"

[package.metadata.shoop-wasm-test]
enabled = true
browser-feature = "wasm-test-browser"

[features]
default = []
wasm-test-browser = ["shoop_wasm_test_support/wasm-test-browser"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
shoop_audio_protocol = { path = "../shoop_audio_protocol" }
shoop_backend = { path = "../shoop_backend" }
shoop_tracing = { workspace = true, default-features = false }
serde_json = { workspace = true }

[dev-dependencies]
assert_no_alloc = { workspace = true }
shoop_wasm_test_support = { path = "../shoop_wasm_test_support" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "=0.3.77"

[lints]
workspace = true
