name: prepare_build_windows
description: Prepare Windows for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - name: Install Qt
    uses: jurplel/install-qt-action@v3
    with:
      version: "6.5.3"
      host: windows
      target: desktop
      arch: win64_mingw
      dir: ${{ runner.temp }}
      setup-python: true
      archives: icu qtbase qtdeclarative qtsvg qtimageformats qtquickcontrols qtquickcontrols2 qtsvg
  - name: Install boost
    id: install_boost
    uses: ./.github/actions/install_boost_headers
    with:
      dir: includes
  - name: Install winget
    uses: Cyberboss/install-winget@v1
  - name: Install pkgconfig lite
    run: winget install --id=bloodrock.pkg-config-lite --disable-interactivity --accept-source-agreements
  - name: Path conversion
    id: pathconvert
    shell: bash
    run: |
      echo "include_dir=$(cygpath -w ${{ steps.install_boost.outputs.include_dir }})" | tee -a $GITHUB_OUTPUT
  - name: Install dependencies and provide build command prefix
    shell: bash
    run: |
      python -m pip install build virtualenv pytest meson
      echo "set \"CMAKE_INCLUDE_PATH=${{ steps.pathconvert.outputs.include_dir }}\" &&" > prepend_build_cmd.txt
