name: prepare_build_windows
description: Prepare Windows for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@v4
    if: always()
    with:
      python-version: '3.9'
  - name: Report python version
    if: always()
    shell: wrap-shell {0}
    run: |
      echo "Default python version is $($PYTHON --version)"

  - name: Setup dependencies
    if: always()
    shell: wrap-shell {0}
    run: |
       curl -L https://github.com/lucasg/Dependencies/releases/download/v1.11.1/Dependencies_x64_Release.zip --output dependencies.zip
       unzip dependencies.zip -d dependencies
       echo "$(cygpath -w $(pwd)/dependencies)" | tee -a $GITHUB_PATH

  - name: Allow running powershell scripts
    if: always()
    shell: pwsh
    run: |
       Set-ExecutionPolicy Unrestricted -Scope CurrentUser
       Get-ExecutionPolicy -List

  - name: Remove GNU link which aliases with MSVC
    if: always()
    shell: wrap-shell {0}
    run: |
      rm -f /c/mingw64/bin/link.exe
      rm -f /usr/bin/link.exe

  - name: Install MSVC 14.40
    if: always()
    shell: pwsh
    run: |
            Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
            $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
            $components= @(
              "Microsoft.VisualStudio.Component.VC.14.40.17.10.x86.x64",
              "Microsoft.VisualStudio.Component.VC.14.40.17.10.CLI.Support"
            )
            [string]$workloadArgs = $components | ForEach-Object {" --add " +  $_}
            $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
            # should be run twice
            $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
            $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden    
