name: prepare_build_windows
description: Prepare Windows for building Shoopdaloop wheels

outputs:
  qt_install_dir:
    description: Place where Qt was installed
    value: ${{ steps.install_qt.outputs.install_dir }}

runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@v4
    with:
      python-version: '3.8' 
  - name: Report python version
    shell: bash
    run: |
      echo "Default python version is $(python --version)"
  - name: Install Qt
    uses: ./.github/actions/install_qt
    id: install_qt
    with:
      url: https://github.com/SanderVocke/shoopdaloop/releases/download/qt-6.6.0-1/qt-6.6.0-windows.tar.gz
  - name: Install boost
    id: install_boost
    uses: ./.github/actions/install_boost_headers
    with:
      dir: includes
  - name: Install winget
    uses: Cyberboss/install-winget@v1
  - name: Install pkgconfig lite
    shell: pwsh
    run: winget install --disable-interactivity --id=bloodrock.pkg-config-lite --disable-interactivity --accept-source-agreements
  - name: Path conversion
    id: pathconvert
    shell: bash
    run: |
      echo "include_dir=$(cygpath -w ${{ steps.install_boost.outputs.include_dir }})" | tee -a $GITHUB_OUTPUT
  - name: Install dependencies and provide build command prefix
    shell: bash
    run: |
      python -m pip install build virtualenv pytest meson
      echo "set \"CMAKE_INCLUDE_PATH=${{ steps.pathconvert.outputs.include_dir }}\" && set \"CMAKE_PREFIX_PATH=${{ steps.install_qt.outputs.install_dir }}/lib/cmake/Qt6\" &&" > prepend_build_cmd.txt
