name: prepare_build_windows
description: Prepare Windows for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@v4
    if: always()
    with:
      python-version: '3.9'
  - name: Report python version
    if: always()
    shell: wrap-shell {0}
    run: |
      echo "Default python version is $($PYTHON --version)"

  - name: Python dependencies
    if: always()
    shell: wrap-shell {0}
    run: |
      $PIP install --upgrade pip build toml

  - name: Setup dependencies
    if: always()
    shell: wrap-shell {0}
    run: |
       curl -L https://github.com/lucasg/Dependencies/releases/download/v1.11.1/Dependencies_x64_Release.zip --output dependencies.zip
       unzip dependencies.zip -d dependencies
       echo "$(cygpath -w $(pwd)/dependencies)" | tee -a $GITHUB_PATH

  - name: Allow running powershell scripts
    if: always()
    shell: pwsh
    run: |
       Set-ExecutionPolicy Unrestricted -Scope CurrentUser
       Get-ExecutionPolicy -List

  - name: Remove GNU link which aliases with MSVC
    if: always()
    shell: wrap-shell {0}
    run: |
      rm -f /c/mingw64/bin/link.exe
      rm -f /usr/bin/link.exe