[package]
name = "shoop_py_wrapped_objects"
edition = "2021"

[dependencies]
shoop_py_utils = { path = "../shoop_py_utils" }
common = { path = "../common" }

ctor = { workspace = true }
log = { workspace = true }
pyo3 = { workspace = true, features = ["auto-initialize"] }
cxx-qt = { workspace = true }
cxx-qt-lib = { workspace = true, features = ["full"] }

[build-dependencies]

[features]
# Dummy build to build dependencies only
prebuild = ["shoop_py_utils/prebuild", "common/prebuild"]