name: post_build_macos
description: Steps after building wheel for MacOS

inputs:
  wheel:
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - name: Passthrough
    id: passthrough
    shell: bash
    run: |
      mkdir -p final_wheel
      cp dist/*.whl final_wheel/