name: post_build_macos
description: Steps after building wheel for MacOS

inputs:
  wheel:
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - name: Delocate
    id: delocate
    shell: sh wrap-shell.sh {0}
    run: |
      python3.9 -m pip install delocate
      /usr/local/bin/delocate-listdeps --all ${{ inputs.wheel }}
  - name: Passthrough
    id: passthrough
    shell: sh wrap-shell.sh {0}
    run: |
      mkdir -p final_wheel
      cp dist/*.whl final_wheel/