name: Rust tests
description: Run archived Rust workspace tests with cargo-nextest

runs:
  using: "composite"
  steps:
  - name: Run Rust workspace tests
    shell: wrap-shell {0}
    if: always() && env.COMMAND_TEST_RUST != ''
    run: |
      ${{ env.RUN_CMD_PREFIX }} ./scripts/run_with_timeout.sh 600 ${{ env.COMMAND_TEST_RUST }}
