[package]
name = "shoop_rs_frontend"
version = "0.2.0"
authors = [
    "Sander Vocke <sandervocke@gmail.com>"
]
edition = "2021"
license = "TODO"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
cxx = "1.0"
cxx-qt = "0.6"
cxx-qt-lib = "0.6"
tempfile = "3.2"
tar = "0.4"
glob = "0.3"
log = "0.4"
colored = "2.1"
fern = { version = "0.6", features = ["colored"] }
humantime = "2.1"
dunce = "1.0"
anyhow = "1.0"
ctor = "0.2"
regex = "1"
shoop_rs_macros = { path = "../shoop_rs_macros" }
shoop_rs_backend = { path = "../shoop_rs_backend" }
shoop_rs_common = { path = "../shoop_rs_common" }

[build-dependencies]
cxx-qt-build = "0.6"
shoop_rs_macros = { path = "../shoop_rs_macros" }