[package]
name = "shoop_app_api"
version.workspace = true
edition = "2021"

[package.metadata.shoop-wasm-test]
enabled = true
browser-feature = "wasm-test-browser"

[features]
default = []
wasm-test-browser = ["shoop_wasm_test_support/wasm-test-browser"]

[dependencies]
shoop_script_resources = { path = "../shoop_script_resources" }

[dev-dependencies]
shoop_wasm_test_support = { path = "../shoop_wasm_test_support" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "=0.3.77"

[lints]
workspace = true
