name: Python Tests
description: Unit tests for Python Qt extensions

inputs:
  variant_name:
    required: true
    type: string
  run_cmd_prefix:
    type: string
    description: "Command-line prefix to use when running the test runner"
  root_path:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - name: prepare
    shell: bash
    run: |
      mkdir -p reports
      echo "results_xml=reports/pytest_${{ inputs.variant_name }}_results.xml" >> $GITHUB_ENV

  - name: pytest (${{ inputs.variant_name }})
    shell: bash
    run: |
      ${{ inputs.run_cmd_prefix }} python3 -m pytest ${{ inputs.root_path }} --junit-xml=${{ env.results_xml }}
      echo "Python test results file: $(ls -la ${{ env.results_xml }})"
  
  - name: Publish Python Test Report
    uses: mikepenz/action-junit-report@v3
    with:
      report_paths: ${{ env.results_xml }}
      detailed_summary: true
      include_passed: true
      check_name: 'python test (${{ inputs.variant_name }})'

