name: post_build_manylinux_2_28
description: Steps after building wheel for manylinux.

inputs:
  wheel:
    required: true
    type: string
    
runs:
  using: "composite"
  steps:
  - name: Auditwheel repair
    shell: wrap-shell.sh {0}
    run: |
      auditwheel repair --plat manylinux_2_28_x86_64 --only-plat -w final_wheel ${{ inputs.wheel }}