# Install a wheel and then build a PyInstaller package from it
 
inputs:
  python:
    description: "Python command"
    required: true
  wheel:
    description: "Wheel to install"
    required: true

outputs:
  distribution:
    description: "Folder where the finished PyInstaller distribution is located"
    value: ${{ steps.pyinstaller.outputs.output }}

runs:
  using: "composite"
  steps:
  - name: PyInstaller
    shell: bash
    id: pyinstaller
    run: |
      export PIP="${{ inputs.python }} -m pip"
      $PIP install --upgrade pip
      $PIP install pyinstaller
      $PIP install ${{ inputs.wheel }}
      export PYINSTALLER=$($PIP show pyinstaller | grep Location | sed 's/Location: //g')/$($PIP show -f pyinstaller | grep -E '.*/pyinstaller' | sed -r 's/^\s+//g')
      echo "Found PyInstaller @ $PYINSTALLER"
      cd distribution/pyinstaller
      $PYINSTALLER shoopdaloop.spec
      tar -czvf shoopdaloop.tar.gz -C dist/shoopdaloop .
      echo "output=distribution/pyinstaller/shoopdaloop.tar.gz" >> $GITHUB_OUTPUT
    