# TODO finish 
 
 
 - name: Prepare PyInstaller
    shell: bash
    id: prepare_pyinstaller
    if: ${{ inputs.pyinstaller == 'true' }}
    run: |
      echo "pyinstaller_dir=$(pwd)/pyinstaller" | tee -a $GITHUB_OUTPUT

  - name: PyInstaller
    shell: bash
    id: pyinstaller
    if: ${{ inputs.pyinstaller == 'true' }}
    run: |
      . $HOME/.bashrc
      cd ${{ steps.install.outputs.install_dir }}
      ${{ inputs.python }} -m pip install ${{ inputs.pip_install_extra_args }} pyinstaller
      pyinstaller __main__.py -n shoopdaloop --collect-all shoopdaloop --collect-all lupa --distpath ${{ steps.prepare_pyinstaller.outputs.pyinstaller_dir }} --clean
  
  - name: Upload PyInstaller distribution (${{ inputs.variant_name }})
    if: ${{ !env.ACT && inputs.pyinstaller == 'true' }}
    uses: actions/upload-artifact@v3
    with:
      name: ${{ inputs.pyinstaller_artifact_name }}
      path: ${{ steps.prepare_pyinstaller.outputs.pyinstaller_dir }}
    