# Install a wheel and then build a PyInstaller package from it
 
inputs:
  python:
    description: "Python command"
    required: true
  pip:
    description: "Pip command"
    required: true
  wheel:
    description: "Wheel to install"
    required: true

outputs:
  distribution:
    description: "Folder where the finished PyInstaller distribution is located"
    value: ${{ steps.pyinstaller.outputs.output }}

runs:
  using: "composite"
  steps:
  - name: PyInstaller
    shell: bash
    id: pyinstaller
    run: |
      ${{ inputs.pip }} install pyinstaller
      ${{ inputs.pip }} install ${{ inputs.wheel }}
      cd distribution/pyinstaller
      ${{ inputs.python }} -m pyinstaller shoopdaloop.spec
      echo "output=distribution/pyinstaller/dist/shoopdaloop" >> $GITHUB_OUTPUT
    