[package]
name = "shoop_egui"
version.workspace = true
edition = "2021"

[dependencies]
shoop_app_api = { path = "../shoop_app_api" }
shoop_settings = { path = "../shoop_settings" }
egui = { workspace = true }
egui_material_icons = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tracy-nextest-capture = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
