[package]
name = "shoop_rs_backend"
version = "0.2.0"
authors = [
    "Sander Vocke <sandervocke@gmail.com>"
]
edition = "2021"
license = "TODO"

[lib]

[dependencies]
anyhow = "1.0"
shoop_rs_common = { path = "../shoop_rs_common" }

[build-dependencies]
bindgen = "0.69"