name: prepare_build_macos
description: Prepare MacOS for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - name: Install packages
    if: always()
    shell: wrap-shell {0}
    run: |
      # Skip if already done (local act builds)
      if [ -f _macos_prepared ]; then
        echo "Already prepared MacOS build, skipping."
        exit 0
      fi

      # Install packages
<<<<<<< Updated upstream
      brew install libtool automake autoconf autoconf-archive cmake
      brew install liblo coreutils pkg-config
      brew install python@3.9
      brew install create-dmg

      python3 -m pip install toml jinja2
=======
      brew install libtool automake autoconf autoconf-archive cmake liblo coreutils ninja create-dmg python@3.9
>>>>>>> Stashed changes
