name: prepare_build_macos
description: Prepare MacOS for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - name: Install packages
    shell: wrap-shell {0}
    run: |
      # Skip if already done (local act builds)
      if [ -f _macos_prepared ]; then
        exit 0
      fi

      # Install packages
      brew install ninja libsndfile libtool automake autoconf cmake
      brew install jack liblo coreutils
      brew install python@3.9
      brew install create-dmg

      # Install Python packages
      python3.9 -m pip install --upgrade pip build
  - name: Install boost
    id: install_boost
    uses: ./.github/actions/install_boost_headers
    with:
      dir: includes
  - name: Set outputs
    shell: wrap-shell {0}
    run: |
      touch _macos_prepared
      echo "CMAKE_INCLUDE_PATH=${{ github.workspace }}/includes LDFLAGS=-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib CFLAGS=-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include CPPFLAGS=-isystem/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include" > prepend_build_cmd.txt