name: prepare_build_macos
description: Prepare MacOS for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - name: Install packages
    shell: bash
    run: |
      # Skip if already done (local act builds)
      if [ -f /macos_prepared ]; then
        exit 0
      fi

      # Install packages
      brew install ninja libsndfile libsamplerate libtool automake autoconf cmake
      brew install jack liblo
      brew install python@3.8

      # Install Python packages
      python3 -m pip install build
  - name: Install Qt
    uses: ./.github/actions/install_qt
    with:
      url: https://github.com/SanderVocke/shoopdaloop/releases/download/qt-6.5.3-1/qt-6.5.3-macos.tar.gz
      dir: ${{ github.workspace }}
  - name: Install boost
    id: install_boost
    uses: ./.github/actions/install_boost_headers
    with:
      dir: includes
  - name: Set outputs
    shell: bash
    run: |
      touch /macos_prepared
      echo "CMAKE_PREFIX_PATH=${{ github.workspace }}/usr/local/Qt-6.5.3 CMAKE_INCLUDE_PATH=${{ github.workspace }}/includes" > prepend_build_cmd.txt