name: prepare_build_macos
description: Prepare MacOS for building Shoopdaloop wheels

runs:
  using: "composite"
  steps:
  - name: Install packages
    if: always()
    shell: wrap-shell {0}
    run: |
      # Skip if already done (local act builds)
      if [ -f _macos_prepared ]; then
        exit 0
      fi

      # Install packages
      brew install ninja libsndfile libtool automake autoconf cmake
      brew install jack liblo coreutils
      brew install python@3.9
      brew install create-dmg

      # Install Python packages
      python3.9 -m pip install --upgrade pip build
      python3.9 -m pip install -r build_python_requirements.txt
  - name: Install boost
    id: install_boost
    if: always()
    uses: ./.github/actions/install_boost_headers
    with:
      dir: includes
  - name: Symlink Qt include folders
    shell: wrap-shell {0}
    if: always()
    run: |
      cd $QT_ROOT_DIR/include
      ln -s ../lib/QtCore.framework/Headers QtCore
      ln -s ../lib/QtGui.framework/Headers QtGui
      ln -s ../lib/QtQml.framework/Headers QtQml
      ln -s ../lib/QtNetwork.framework/Headers QtNetwork
      ln -s ../lib/QtQuick.framework/Headers QtQuick
  - name: Set outputs
    if: always()
    shell: wrap-shell {0}
    run: |
      touch _macos_prepared
      echo "CMAKE_INCLUDE_PATH=$CMAKE_INCLUDE_PATH ${{ github.workspace }}/includes" | tee -a $GITHUB_ENV
      echo "LDFLAGS=$LDFLAGS -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib" | tee -a $GITHUB_ENV
      echo "CFLAGS=$CFLAGS -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include CPPFLAGS=-isystem/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include" | tee -a $GITHUB_ENV