name: post_build_manylinux_2_31
description: Steps after building wheel for manylinux.

inputs:
  wheel:
    required: true
    type: string
    
runs:
  using: "composite"
  steps:
  - name: Auditwheel repair
    shell: wrap-shell.sh {0}
    run: |
      auditwheel repair --plat manylinux_2_31_${{ matrix.arch }} --only-plat -w final_wheel ${{ inputs.wheel }}