name: Screenshots
description: Runs the app and saves window screenshots for inspection.

inputs:
  root_path:
    type: string
    required: true
  screenshots_path:
    type: string
    required: false
    default: /tmp/screenshots
  artifact_name:
    required: true
    type: string
  python:
    type: string
    default: python

runs:
  using: "composite"
  steps:
  - name: Save screenshots
    if: always()
    shell: wrap-shell {0}
    run: >
        LIBGL_ALWAYS_SOFTWARE=1
        SHOOP_LOG=Frontend.TestScreenGrabber=debug
        ${{ env.RUN_CMD_PREFIX }}
        timeout 3m ${{ env.COMMAND_SHOOPDALOOP }} -b dummy --test-grab-screens ${{ inputs.screenshots_path }}

  - name: Upload screenshots
    if: always()
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.artifact_name }}
      path: ${{ inputs.screenshots_path }}


