name: Screenshots
description: Runs the app and saves window screenshots for inspection.

inputs:
  root_path:
    type: string
    required: true
  screenshots_path:
    type: string
    required: false
    default: /tmp/screenshots
  shoopdaloop_command:
    type: string
    required: true
  artifact_name:
    required: true
    type: string
  qt_qpa_platform:
    type: string
    default: vnc
  python:
    type: string
    default: python
  run_cmd_prefix:
    type: strint

runs:
  using: "composite"
  steps:
  - name: Save screenshots
    shell: wrap-shell {0}
    run: |
        LIBGL_ALWAYS_SOFTWARE=1 QT_QPA_PLATFORM=${{ inputs.qt_qpa_platform }} SHOOP_LOG=Frontend.TestScreenGrabber=debug ${{ inputs.run_cmd_prefix }} ${{ inputs.shoopdaloop_command }} -b dummy --test-grab-screens ${{ inputs.screenshots_path }}
  
  - name: Upload screenshots
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.artifact_name }}
      path: ${{ inputs.screenshots_path }}


