name: Install Boost headers
description: Install boost headers

inputs:
  dir:
    description: "Directory where boost headers will be installed"
    required: false
    default: "/usr/include"

outputs:
  include_dir:
    description: "Place where headers of boost can be found"
    value: ${{ steps.boost.outputs.include_dir }}

runs:
  using: "composite"
  steps:
  - name: Install Boost headers
    id: boost
    shell: bash
    run: |
      set -x
      
      # Skip if already done (local act builds)
      if [ -f _boost_headers_installed ]; then
        exit 0
      fi

      export includes_dir="$(cygpath ${{ inputs.dir }})"
      echo "Installing boost headers to $includes_dir"

      # Install Boost
      curl -L https://boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.gz --output boost.tar.gz
      tar -xzf boost.tar.gz
      mkdir -p $includes_dir
      cp -r boost_1_82_0/boost $includes_dir/boost

      touch _boost_headers_installed

      echo "include_dir=$includes_dir" | tee -a $GITHUB_OUTPUT