#!/bin/sh

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

export LD_LIBRARY_PATH="${APPDIR}/lib:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${APPDIR}/shoop_lib:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${APPDIR}/lib:${LD_LIBRARY_PATH}"

${SCRIPT_DIR}/shoopdaloop $@