#!/bin/sh

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

if [ ! -f $SCRIPT_DIR/shoop_lib/test_runner ]; then
    echo "Backend tests were not bundled in this app." >&2
    exit 1;
else
    $SCRIPT_DIR/shoop_lib/test_runner $@
fi