#!/bin/sh

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

export LD_LIBRARY_PATH="${APPDIR}/lib:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${APPDIR}/shoop_lib:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${APPDIR}/lib:${LD_LIBRARY_PATH}"

if [ ! -f $SCRIPT_DIR/shoop_lib/test_runner ]; then
    echo "Backend tests were not bundled in this AppImage." >&2
    exit 1;
else
    $SCRIPT_DIR/shoop_lib/test_runner $@
fi