#!/bin/sh

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

export LD_LIBRARY_PATH="${APPDIR}/lib:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${APPDIR}/shoop_lib:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${APPDIR}/lib:${LD_LIBRARY_PATH}"

PYSIDE6_LIBS=$(find $SCRIPT_DIR -wholename "*/site-packages/PySide6/Qt/lib")
export LD_LIBRARY_PATH="${PYSIDE6_LIBS}:${LD_LIBRARY_PATH}"

if [ ! -f $SCRIPT_DIR/cargo-nextest ]; then
    echo "Rust tests were not bundled in this AppImage." >&2
    exit 1;
else
    $SCRIPT_DIR/cargo-nextest nextest run --archive-file $SCRIPT_DIR/nextest-archive.tar.zst $@
fi