[package]
name = "crashhandling"
edition = "2021"

[dependencies]
common = { path = "../common" }
minidumper = { workspace = true }
crash-handler = { workspace = true }
ctor = { workspace = true }
log = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
tempfile = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
once_cell = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }

[features]
# Dummy build to build dependencies only
prebuild = []