name: Build Wheel

on:
  workflow_call:
    inputs:
      variant_name:
        required: true
        type: string
      pypa_build_extra_args:
        required: false
        type: string
      whl_suffix:
        required: false
        type: string
    outputs:
      run_cmd_prefix:
        description: "Command-line prefix to use when running the apps in the built wheel"
        value: ${{ jobs.build_whl.outputs.run_cmd_prefix }}

jobs:

  build_whl:
    runs-on: ubuntu-latest
    outputs:
      run_cmd_prefix: ${{ steps.build.outputs.run_cmd_prefix }}
    container:
      image: sandervocke/shoopdaloop_ubuntu_kinetic_build_base:latest
      options: --user root --workdir /
    
    steps:      
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build wheel (${{ inputs.variant_name }})
      id: build
      run: |
        python3 -m build -w ${{ inputs.pypa_build_extra_args }}
        echo "run_cmd_prefix=$(find . -name run_cmd_prefix.txt -exec cat {} \;)" >> $GITHUB_OUTPUT
        cd dist
        for f in *.whl; do mv -- "$f" "${f%.whl}${{ inputs.whl_suffix }}.whl"; done
        echo "wheel=$(ls *.whl)" >> $GITHUB_OUTPUT
    
    - name: Upload wheel (${{ inputs.variant_name }})
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.variant_name }}_wheel
        path: dist/${{ steps.build.outputs.wheel }}

