name: Build and upload dependencies

on:
  push:
    branches: [ "*" ]
    tags: "v*.*.*"
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            name-suffix: linux.x86-64
            container: "docker.io/sandervocke/shoopdaloop_build_base_debian_bullseye_x86_64:latest"
          - runs-on: ubuntu-latest
            name-suffix: linux.arm
            conatainer: "docker.io/sandervocke/shoopdaloop_build_base_debian_bullseye_arm64:latest"
          - runs-on: macos-14
            name-suffix: macos.arm
          - runs-on: macos-12
            name-suffix: macos.x86-64
          - runs-on: windows-2022
            name-suffix: windows.x86-64
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build LV2
        uses: ./.github/actions/build_and_upload_meson_dependency
        with:
           name: lv2.v1.18.10.${{ matrix.name-suffix }}
           repo: https://github.com/lv2/lv2.git
           git_rev: v1.18.10
           meson_options: --default-library=shared
