name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug
  BUILD_DEPENDS_ARCH: qt6 qt6-declarative jack2 lv2 lilv boost spdlog fmt shiboken6 python git cmake ninja pkgconf pyside6 python-pip nlohmann-json xorg-xinit xf86-video-dummy xorg-server jack2
  BUILD_DEPENDS_PYTHON: ctypesgen
  RUN_DEPENDS_PYTHON: playsound resampy mido jsonschema numpy scipy soundfile pyjacklib
  XORG_CONFIG: |
    Section "Monitor"
            Identifier "dummy_monitor"
            HorizSync 28.0-80.0
            VertRefresh 48.0-75.0
            Modeline "1920x1080" 172.80 1920 2040 2248 2576 1080 1081 1084 1118
    EndSection

    Section "Device"
            Identifier "dummy_card"
            VideoRam 256000
            Driver "dummy"
    EndSection

    Section "Screen"
            Identifier "dummy_screen"
            Device "dummy_card"
            Monitor "dummy_monitor"
            SubSection "Display"
            EndSubSection
    EndSection

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    
    steps:
    - name: Install Arch packages
      run: |
        pacman --noconfirm -Syy && pacman --noconfirm -S --needed --overwrite "*" ${BUILD_DEPENDS_ARCH}
    
    - name: Set up virtual display
      run: |
        mkdir -p /etc/X11/xorg.conf.d
        echo "${XORG_CONFIG}" > /tmp/x_config.conf
        
    - name: Install Python packages
      run: |
        pacman -S --noconfirm --needed --overwrite "*" python-wheel
        pip install --upgrade --break-system-packages setuptools
        pip install --break-system-packages ${BUILD_DEPENDS_PYTHON}
        pip install --break-system-packages ${RUN_DEPENDS_PYTHON}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: |
        cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: FIXME symbolic back-end link to build folder
      run: |
        ln -s ${{github.workspace}}/build build

    - name: Build CMake
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Back-end tests
      if: success() || failure() # always run even if the previous step fails
      run: |
        mkdir -p reports
        ${{github.workspace}}/build/backend/test/test_runner --reporter junit --out reports/backend_junit_results.xml
        echo "Back-end test results file: $(ls -la reports/backend_junit_results.xml)"
    
    - name: QML tests
      if: success() || failure() # always run even if the previous step fails
      run: |
        mkdir -p reports
        X -config /tmp/x_config.conf &
        sleep 0.5
        DISPLAY=:0 ./test/run_qml_tests.py --junit reports/qml_junit_results.xml

    - name: Publish Backend Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: 'reports/backend_junit_results.xml'
        detailed_summary: true
        include_passed: true
        check_name: 'Backend Test Report'
    
    - name: Publish QML Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: 'reports/qml_junit_results.xml'
        detailed_summary: true
        include_passed: true
        check_name: 'QML Test Report'
