name: Build and push CI containers

on: workflow_dispatch

permissions:
  contents: read
  checks: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Prepare tag name
        run: |
          echo "UNIQUETAG=$(date +"%Y%m%d")_git_$(git rev-parse HEAD | cut -c1-8)" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: dist
          file: dist/dockerfiles/arch_build/arch_build.Dockerfile
          push: true
          tags: sandervocke/shoopdaloop_build_arch:latest
      -
        name: Unique tag
        run: |
          docker tag sandervocke/shoopdaloop_build_arch:latest sandervocke/shoopdaloop_build_arch:${UNIQUETAG}
          docker push sandervocke/shoopdaloop_build_arch:${UNIQUETAG}