name: Build Qt

on: workflow_dispatch

permissions:
  contents: read
  checks: write

jobs:
  build_qt:
    runs-on: ubuntu-latest
    container:
      image: sandervocke/shoopdaloop_build_qt_manylinux_2_28:latest
      options: --user root --workdir /
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Qt
      uses: ./.github/actions/build_qt
      with:
        install: false
        upload: true
        cache: false
        force-rebuild: true
  