name: Docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: graphviz plantuml
          version: 1.0

      - name: Install dependencies
        run: |
          pip install sphinx sphinx-material sphinxcontrib.fulltoc sphinxcontrib.plantuml

      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
      
      - name: Store HTML as artifact
        uses: actions/upload-artifact@v3
        with:
          name: html
          path: _build/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true