name: MacOS TMate test session

on: workflow_dispatch

permissions:
  contents: read
  checks: write

jobs:
  tmate:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup tmate session
      uses: SanderVocke/action-tmate@master
  