# Build a meson project and upload it

inputs:
  name:
    description: "name of the dependency"
  repo:
    description: "repository URL"
  git_rev:
    description: "git revision to build"
  meson_options:
    description: "additional meson configure options"

runs:
  using: "composite"
  steps:

  - shell: bash
    run: |
       git clone ${{ inputs.repo }} ${{ inputs.name }}
       cd ${{ inputs.name }}
       git checkout ${{ inputs.git_rev }}
       mkdir ${{ inputs.name }}
       mkdir build

  - uses: BSFishy/meson-build@v1.0.3
    with:
      action: install
      directory: build
      setup-options: ${{ inputs.meson_options }}

  - name: Upload
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.name }}
      path: ${{ github.workspace }}/${{ inputs.name }}/${{ inputs.name }}

