# Build a meson project and upload it

inputs:
  name:
    description: "name of the dependency"
  repo:
    description: "repository URL"
  git_rev:
    description: "git revision to build"
  meson_options:
    description: "additional meson configure options"

runs:
  using: "composite"
  steps:

  - shell: wrap-shell {0}
    run: |
       git clone ${{ inputs.repo }} ${{ inputs.name }}
       cd ${{ inputs.name }}
       git checkout ${{ inputs.git_rev }}
       mkdir ${{ inputs.name }}
       mkdir build
       $MESON setup --prefix=$(pwd)/${{ inputs.name }} build .
       cd build
       $MESON compile
       $MESON install

  - name: Upload
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.name }}
      path: ${{ github.workspace }}/${{ inputs.name }}/${{ inputs.name }}

